import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { allowedNextStatuses, SHIPMENT_STATUSES } from "@/lib/admin-orders";
import { dateTime, paise } from "@/lib/admin-shop";
import { ConfirmSubmit } from "@/components/admin/ConfirmSubmit";
import { addOrderNoteAction, cancelOrderAction, initiateRefundAction, updateOrderStatusAction, updateShipmentAction, verifyPaymentAction } from "../actions";

export const dynamic="force-dynamic";
const card="rounded-2xl border border-stone-200 bg-white p-5 shadow-sm";
const row=(label:string,value:React.ReactNode)=><div className="flex justify-between gap-4 border-b border-stone-100 py-2 text-sm"><span className="text-stone-500">{label}</span><b className="text-right text-stone-900">{value||"—"}</b></div>;
export default async function OrderDetailPage({params,searchParams}:{params:Promise<{orderId:string}>;searchParams:Promise<{notice?:string;error?:string}>}){
  const {orderId}=await params;const message=await searchParams;
  const order=await prisma.shopOrder.findUnique({where:{id:orderId},include:{user:true,product:true,statusHistory:{include:{adminUser:true},orderBy:{createdAt:"desc"}},trackingEvents:{include:{adminUser:true},orderBy:{createdAt:"desc"}},adminNotes:{include:{adminUser:true},orderBy:{createdAt:"desc"}},paymentVerification:true,refunds:{include:{adminUser:true},orderBy:{initiatedAt:"desc"}}}});
  if(!order)notFound();const next=allowedNextStatuses(order.orderStatus);
  const image=order.product.imageMimeType?`/api/v1/shop/products/${order.productId}/image`:order.product.imageUrl;
  return <div className="mx-auto max-w-[100rem] space-y-6">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><Link href="/admin/orders" className="text-sm font-bold text-amber-700">← All orders</Link><h1 className="mt-2 font-display text-4xl font-bold">{order.orderNumber}</h1><p className="mt-2 text-stone-600">Complete payment, fulfilment, delivery and audit record.</p></div><div className="flex flex-wrap gap-2"><a href={`/api/v1/admin/orders/${order.id}/document?type=invoice`} className="rounded-xl border bg-white px-4 py-3 font-bold">Print invoice</a><a href={`/api/v1/admin/orders/${order.id}/document?type=invoice&download=1`} className="rounded-xl border bg-white px-4 py-3 font-bold">Download invoice</a><a href={`/api/v1/admin/orders/${order.id}/document?type=packing-slip`} className="rounded-xl bg-stone-950 px-4 py-3 font-bold text-amber-300">Packing slip</a></div></div>
    {(message.notice||message.error)&&<div className={`rounded-xl p-4 font-bold ${message.error?"bg-red-50 text-red-800":"bg-emerald-50 text-emerald-800"}`}>{message.error||message.notice}</div>}
    <section className="grid gap-5 xl:grid-cols-3">
      <article className={card}><h2 className="text-xl font-black">Customer</h2>{row("Full name",order.customerName||order.user.fullName)}{row("Email",order.customerEmail||order.user.email)}{row("Mobile",order.customerPhone||order.user.phone)}{row("Account ID",order.userId)}<div className="mt-4 flex gap-2">{(order.customerEmail||order.user.email)&&<a href={`mailto:${order.customerEmail||order.user.email}`} className="rounded-lg bg-amber-400 px-3 py-2 text-sm font-bold">Email customer</a>}{(order.customerPhone||order.user.phone)&&<a href={`tel:${order.customerPhone||order.user.phone}`} className="rounded-lg border px-3 py-2 text-sm font-bold">Call</a>}</div></article>
      <article className={card}><h2 className="text-xl font-black">Product</h2>{image&&<div className="relative my-4 h-36 rounded-xl bg-stone-50"><Image src={image} alt={order.productName} fill className="object-contain p-3"/></div>}{row("Product",order.productName)}{row("Metal",order.metalType)}{row("Purity",order.purity)}{row("Weight",`${order.weightGrams}g`)}{row("Quantity",order.quantity)}</article>
      <article className={card}><h2 className="text-xl font-black">Price</h2>{row("Metal value",paise(order.metalValuePaise))}{row("Service charge",paise(order.serviceChargePaise))}{row("GST",paise(order.gstPaise))}{row("Shipping",order.shippingAmountPaise===0n?"FREE":paise(order.shippingAmountPaise))}{row("Discount",paise(order.discountAmountPaise))}{row("Total payable",paise(order.totalAmountPaise))}</article>
      <article className={card}><h2 className="text-xl font-black">Payment</h2>{row("Gateway",order.gateway)}{row("Gateway order ID",order.gatewayOrderId)}{row("Gateway payment ID",order.gatewayPaymentId)}{row("Payment status",order.paymentStatus)}{row("Paid amount",order.paymentStatus==="SUCCESS"?paise(order.totalAmountPaise):"—")}{row("Paid date",order.paidAt?dateTime(order.paidAt):"—")}{row("Verification",order.paymentVerification?.result||"Not verified")}{row("Verification result",order.paymentVerification?.resultMessage)}{!order.paymentVerification&&order.paymentStatus!=="SUCCESS"&&<form action={verifyPaymentAction} className="mt-4"><input type="hidden" name="orderId" value={order.id}/><ConfirmSubmit message="Re-verify this payment with the configured gateway?" className="rounded-lg bg-emerald-600 px-4 py-2 font-bold text-white">Verify payment</ConfirmSubmit></form>}</article>
      <article className={card}><h2 className="text-xl font-black">Delivery snapshot</h2>{row("Address",`${order.addressLine1||""}${order.addressLine2?`, ${order.addressLine2}`:""}`)}{row("Landmark",order.landmark)}{row("City",order.deliveryCity)}{row("District",order.deliveryDistrict)}{row("State",order.deliveryState)}{row("PIN code",order.deliveryPincode)}{row("Country",order.deliveryCountry)}</article>
      <article className={card}><h2 className="text-xl font-black">Shipment</h2>{row("Courier",order.courierPartner)}{row("AWB / Tracking",order.trackingNumber)}{row("Shipment ID",order.shipmentId||order.shiprocketShipmentId)}{row("Pickup",order.pickupAt?dateTime(order.pickupAt):"—")}{row("Status",order.shipmentStatus)}{row("Expected delivery",order.expectedDeliveryAt?dateTime(order.expectedDeliveryAt):"—")}{row("Delivered",order.deliveredAt?dateTime(order.deliveredAt):"—")}{order.publicTrackingUrl&&<a href={order.publicTrackingUrl} target="_blank" rel="noreferrer" className="mt-3 inline-block font-bold text-amber-700">Open public tracking →</a>}</article>
    </section>
    <section className="grid gap-6 xl:grid-cols-2">
      <article className={card}><h2 className="text-xl font-black">Order workflow</h2><p className="mt-1 text-sm text-stone-500">Current: {order.orderStatus}. Only valid next states are available.</p>{next.length?<form action={updateOrderStatusAction} className="mt-4 grid gap-3"><input type="hidden" name="orderId" value={order.id}/><select name="status" className="rounded-xl border p-3">{next.map(x=><option key={x}>{x}</option>)}</select><textarea name="internalNote" placeholder="Optional private transition note" className="rounded-xl border p-3"/><ConfirmSubmit message="Apply this status transition?" className="rounded-xl bg-amber-400 p-3 font-black">Update status</ConfirmSubmit></form>:<p className="mt-4 rounded-xl bg-stone-50 p-4">No further direct transition is available.</p>}</article>
      <article className={card}><h2 className="text-xl font-black">Manual shipment management</h2><form action={updateShipmentAction} className="mt-4 grid gap-3 sm:grid-cols-2"><input type="hidden" name="orderId" value={order.id}/><input name="courierPartner" defaultValue={order.courierPartner||""} placeholder="Courier partner" className="rounded-xl border p-3"/><input name="trackingNumber" defaultValue={order.trackingNumber||""} placeholder="AWB / tracking number" className="rounded-xl border p-3"/><input name="shipmentId" defaultValue={order.shipmentId||""} placeholder="Shipment ID" className="rounded-xl border p-3"/><input name="publicTrackingUrl" defaultValue={order.publicTrackingUrl||""} type="url" placeholder="Public tracking URL" className="rounded-xl border p-3"/><input name="pickupAt" type="datetime-local" className="rounded-xl border p-3"/><input name="expectedDeliveryAt" type="datetime-local" className="rounded-xl border p-3"/><select name="shipmentStatus" defaultValue={order.shipmentStatus} className="rounded-xl border p-3">{SHIPMENT_STATUSES.map(x=><option key={x}>{x}</option>)}</select><input required name="publicMessage" placeholder="Customer-visible tracking update" className="rounded-xl border p-3"/><textarea name="internalNote" placeholder="Optional private note" className="rounded-xl border p-3 sm:col-span-2"/><ConfirmSubmit message="Publish this shipment update to the customer?" className="rounded-xl bg-stone-950 p-3 font-black text-amber-300 sm:col-span-2">Save shipment and timeline</ConfirmSubmit></form></article>
      <article className={card}><h2 className="text-xl font-black">Private admin notes</h2><form action={addOrderNoteAction} className="mt-4 flex gap-2"><input type="hidden" name="orderId" value={order.id}/><input required name="body" maxLength={2000} placeholder="Add an immutable private note" className="min-w-0 flex-1 rounded-xl border p-3"/><button className="rounded-xl bg-stone-900 px-4 font-bold text-white">Add</button></form><div className="mt-4 space-y-3">{order.adminNotes.map(note=><div key={note.id} className="rounded-xl bg-stone-50 p-3 text-sm"><p>{note.body}</p><p className="mt-2 text-xs text-stone-500">{note.adminUser.name||note.adminUser.email} · {dateTime(note.createdAt)}</p></div>)}{!order.adminNotes.length&&<p className="text-stone-500">No private notes.</p>}</div></article>
      <article className={card}><h2 className="text-xl font-black">Customer tracking timeline</h2><div className="mt-4 border-l border-amber-300 pl-5">{order.trackingEvents.map(event=><div key={event.id} className="relative pb-5"><span className="absolute -left-[1.45rem] top-1 h-2 w-2 rounded-full bg-amber-500"/><b>{event.status}</b><p className="text-sm">{event.publicMessage}</p><p className="text-xs text-stone-500">{dateTime(event.createdAt)} · {event.source}</p></div>)}{!order.trackingEvents.length&&<p className="text-stone-500">No tracking events yet.</p>}</div></article>
      <article className={`${card} border-red-200`}><h2 className="text-xl font-black text-red-800">Cancellation</h2><form action={cancelOrderAction} className="mt-4 grid gap-3"><input type="hidden" name="orderId" value={order.id}/><textarea required name="reason" placeholder="Required cancellation reason" className="rounded-xl border p-3"/><label><input type="checkbox" name="paymentCaptured"/> Payment was captured</label><label><input type="checkbox" name="refundRequired"/> Refund is required</label><label><input type="checkbox" name="shipmentCreated"/> Shipment was created</label><ConfirmSubmit message="Cancel this order? This action is audited." className="rounded-xl bg-red-700 p-3 font-black text-white">Cancel order</ConfirmSubmit></form></article>
      <article className={card}><h2 className="text-xl font-black">Refund management</h2><form action={initiateRefundAction} className="mt-4 grid gap-3"><input type="hidden" name="orderId" value={order.id}/><input required name="amount" type="number" step=".01" min=".01" max={Number(order.totalAmountPaise)/100} placeholder="Refund amount" className="rounded-xl border p-3"/><textarea required name="reason" placeholder="Required refund reason" className="rounded-xl border p-3"/><ConfirmSubmit message="Create a pending gateway refund record?" className="rounded-xl bg-amber-400 p-3 font-black">Initiate refund</ConfirmSubmit></form><div className="mt-4">{order.refunds.map(refund=><p key={refund.id} className="border-t py-2 text-sm">{paise(refund.amountPaise)} · {refund.status} · {refund.reason}</p>)}</div></article>
    </section>
    <section className={card}><h2 className="text-xl font-black">Order status audit history</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[800px] text-left text-sm"><thead><tr><th className="p-2">Status</th><th>Customer message</th><th>Source</th><th>Admin</th><th>Timestamp</th></tr></thead><tbody>{order.statusHistory.map(item=><tr key={item.id} className="border-t"><td className="p-2 font-bold">{item.status}</td><td>{item.publicMessage}</td><td>{item.source}</td><td>{item.adminUser?.email||"System"}</td><td>{dateTime(item.createdAt)}</td></tr>)}</tbody></table></div></section>
  </div>;
}
