import "server-only";
import { prisma } from "@/lib/prisma";
export type ShiprocketConfig={enabled:boolean;baseUrl:string;email:string;password:string;pickupLocation:string;webhookSecret:string;lengthCm:number;breadthCm:number;heightCm:number;weightKg:number;mode:"Surface"|"Air"};
const positive=(value:string|undefined)=>{const number=Number(value);return Number.isFinite(number)&&number>0?number:0};
export async function getShiprocketConfig():Promise<ShiprocketConfig>{const saved=await prisma.systemSetting.findUnique({where:{key:"SHIPROCKET_PICKUP_LOCATION"}});return {enabled:process.env.SHIPROCKET_ENABLED==="true",baseUrl:(process.env.SHIPROCKET_BASE_URL||"https://apiv2.shiprocket.in/v1/external").replace(/\/$/,""),email:process.env.SHIPROCKET_EMAIL||"",password:process.env.SHIPROCKET_PASSWORD||"",pickupLocation:saved?.value||process.env.SHIPROCKET_PICKUP_LOCATION||"",webhookSecret:process.env.SHIPROCKET_WEBHOOK_SECRET||"",lengthCm:positive(process.env.SHIPROCKET_DEFAULT_LENGTH_CM),breadthCm:positive(process.env.SHIPROCKET_DEFAULT_BREADTH_CM),heightCm:positive(process.env.SHIPROCKET_DEFAULT_HEIGHT_CM),weightKg:positive(process.env.SHIPROCKET_DEFAULT_WEIGHT_KG),mode:process.env.SHIPROCKET_DEFAULT_MODE?.toLowerCase()==="air"?"Air":"Surface"}}
export function validateShiprocketConfig(config:ShiprocketConfig){if(!config.enabled)return {ok:false as const,code:"SHIPROCKET_DISABLED",message:"Shiprocket integration disabled."};if(!config.email||!config.password)return {ok:false as const,code:"SHIPROCKET_NOT_CONFIGURED",message:"Shiprocket API-user credentials are missing."};if(!config.baseUrl.startsWith("https://"))return {ok:false as const,code:"SHIPROCKET_NOT_CONFIGURED",message:"Shiprocket base URL must use HTTPS."};return {ok:true as const}}
export function requirePackageConfig(config:ShiprocketConfig){const validation=validateShiprocketConfig(config);if(!validation.ok)throw new ShiprocketError(validation.code,validation.message);if(!config.pickupLocation)throw new ShiprocketError("PICKUP_LOCATION_MISSING","Select a valid Shiprocket pickup location.");if(!config.lengthCm||!config.breadthCm||!config.heightCm||!config.weightKg)throw new ShiprocketError("SHIPROCKET_NOT_CONFIGURED","Default package dimensions and weight must be positive.")}
export class ShiprocketError extends Error{constructor(public code:string,message:string,public status=400){super(message);this.name="ShiprocketError"}}
export function publicShiprocketHealth(config:ShiprocketConfig){const validation=validateShiprocketConfig(config);return {enabled:config.enabled,configured:validation.ok,pickupLocation:config.pickupLocation||null,mode:config.mode,packageConfigured:Boolean(config.lengthCm&&config.breadthCm&&config.heightCm&&config.weightKg),message:validation.ok?"Shiprocket API credentials configured.":validation.message}}
