import "server-only";
import { createHash, randomUUID } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { allowedNextStatuses } from "@/lib/admin-order-transitions";
import { getShiprocketConfig, requirePackageConfig, ShiprocketError } from "./config";
import { shiprocketRequest } from "./client";
import { mapShiprocketStatus, shouldApplyTracking } from "./tracking";
import type { Prisma } from "@/generated/prisma/client";
import { enqueueNotification } from "@/lib/notifications/outbox";

type Admin={id:string;ipAddress:string|null};
const hash=(value:unknown)=>createHash("sha256").update(JSON.stringify(value)).digest("hex");
const string=(value:unknown)=>value==null?"":String(value);
const number=(value:unknown)=>{const parsed=Number(value);return Number.isFinite(parsed)?parsed:0};
const validUrl=(value:unknown)=>{if(typeof value!=="string")return null;try{const url=new URL(value);return url.protocol==="https:"?url.toString():null}catch{return null}};
const operationKey=(orderId:string,type:string,qualifier="once")=>`${orderId}:${type}:${qualifier}`;
async function beginOperation(orderId:string,type:string,payload:unknown,key=operationKey(orderId,type)){
  const fingerprint=hash(payload),existing=await prisma.shiprocketOperation.findUnique({where:{idempotencyKey:key}});
  if(existing?.status==="SUCCESS")return {duplicate:true as const,operation:existing};
  if(existing?.status==="PENDING"&&Date.now()-existing.attemptedAt.getTime()<120_000)throw new ShiprocketError("INVALID_SHIPMENT_STATE",`${type} is already in progress.`);
  const operation=existing?await prisma.shiprocketOperation.update({where:{id:existing.id},data:{status:"PENDING",attemptedAt:new Date(),retryCount:{increment:1},errorCode:null,errorMessage:null}}):await prisma.shiprocketOperation.create({data:{shopOrderId:orderId,operationType:type,idempotencyKey:key,requestFingerprint:fingerprint}});
  return {duplicate:false as const,operation};
}
async function finishOperation(id:string,success:boolean,reference?:string,error?:unknown){await prisma.shiprocketOperation.update({where:{id},data:{status:success?"SUCCESS":"FAILED",responseReference:reference?.slice(0,200),errorCode:error instanceof ShiprocketError?error.code:"PROVIDER_TEMPORARILY_UNAVAILABLE",errorMessage:error instanceof Error?error.message.slice(0,500):null,completedAt:new Date()}})}
async function audit(admin:Admin|undefined,orderId:string,action:string,details:Record<string,unknown>){if(!admin)return;await prisma.adminAuditLog.create({data:{adminUserId:admin.id,action,targetEntity:"ShopOrder",targetId:orderId,detailsJson:details as Prisma.InputJsonValue,ipAddress:admin.ipAddress}})}
async function notify(orderId:string,eventType:string,message:string){const order=await prisma.shopOrder.findUnique({where:{id:orderId},select:{userId:true,orderNumber:true}});if(!order)return;await enqueueNotification({customerId:order.userId,shopOrderId:orderId,eventType,title:"RateStack shipment update",body:message,payload:{deepLink:`/shop/orders/${orderId}`,orderId},deduplicationKey:`shipment:${orderId}:${eventType}:${message}`})}
export function assertShipmentEligibility(order:{paymentStatus:string;orderStatus:string;shiprocketOrderId:string|null;customerName:string|null;customerPhone:string|null;addressLine1:string|null;deliveryCity:string|null;deliveryState:string|null;deliveryPincode:string|null;productName:string;quantity:number}){
  if(order.paymentStatus!=="SUCCESS"||!["PAYMENT_VERIFIED","ORDER_CONFIRMED","PROCESSING","PACKED","READY_TO_SHIP"].includes(order.orderStatus))throw new ShiprocketError("INVALID_SHIPMENT_STATE","Payment must be verified and the order confirmed before shipment creation.");
  if(order.shiprocketOrderId)throw new ShiprocketError("INVALID_SHIPMENT_STATE","An active Shiprocket order already exists.");
  if(!order.customerName||!order.customerPhone||!order.addressLine1||!order.deliveryCity||!order.deliveryState||!order.deliveryPincode)throw new ShiprocketError("INVALID_SHIPMENT_STATE","The saved delivery snapshot is incomplete.");
  if(!order.productName||order.quantity<1)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Saved product details are incomplete.");
}
export async function createShiprocketShipment(orderId:string,admin?:Admin){
  const config=await getShiprocketConfig();requirePackageConfig(config);const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});assertShipmentEligibility(order);
  const payload={order_id:order.orderNumber,order_date:order.createdAt.toISOString().slice(0,10),pickup_location:config.pickupLocation,billing_customer_name:order.customerName,billing_last_name:"",billing_address:order.addressLine1,billing_address_2:order.addressLine2||"",billing_city:order.deliveryCity,billing_pincode:order.deliveryPincode,billing_state:order.deliveryState,billing_country:order.deliveryCountry||"India",billing_email:order.customerEmail||"",billing_phone:order.customerPhone,shipping_is_billing:true,order_items:[{name:order.productName,sku:`RS-${order.productId}-${order.weightGrams}G`,units:order.quantity,selling_price:Number(order.totalAmountPaise)/100,discount:Number(order.discountAmountPaise)/100,tax:Number(order.gstPaise)/100,hsn:"7113"}],payment_method:"Prepaid",sub_total:Number(order.totalAmountPaise)/100,length:config.lengthCm,breadth:config.breadthCm,height:config.heightCm,weight:config.weightKg};
  const op=await beginOperation(orderId,"CREATE_ORDER",payload);if(op.duplicate)return order;
  try{const response=await shiprocketRequest("/orders/create/adhoc",{method:"POST",body:payload});const providerOrderId=string(response.order_id),shipmentId=string(response.shipment_id);if(!providerOrderId||!shipmentId)throw new ShiprocketError("SHIPROCKET_ORDER_CREATE_FAILED","Shiprocket did not return order and shipment identifiers.",502);const updated=await prisma.shopOrder.update({where:{id:orderId},data:{shiprocketOrderId:providerOrderId,shiprocketShipmentId:shipmentId,shiprocketChannelOrderId:order.orderNumber,shipmentId,shipmentCreatedAt:new Date(),shiprocketStatusText:string(response.status)||"ORDER CREATED",shiprocketIntegrationStatus:"ORDER_CREATED",shiprocketFailureReason:null}});await Promise.all([finishOperation(op.operation.id,true,providerOrderId),audit(admin,orderId,"SHIPROCKET_ORDER_CREATED",{providerOrderId,shipmentId}),notify(orderId,"SHIPMENT_CREATED","Your shipment record has been created and is being prepared.")]);return updated}catch(error){if(error instanceof ShiprocketError&&error.code==="PROVIDER_TEMPORARILY_UNAVAILABLE"){try{const reconciliation=await shiprocketRequest(`/orders?search=${encodeURIComponent(order.orderNumber)}`,{safeRetry:true}),matches=(Array.isArray(reconciliation.data)?reconciliation.data:[]) as Record<string,unknown>[],match=matches.find(item=>string(item.channel_order_id||item.order_id)===order.orderNumber);if(match){const providerOrderId=string(match.id||match.order_id),shipmentId=string(match.shipments&&Array.isArray(match.shipments)?(match.shipments[0] as Record<string,unknown>)?.id:match.shipment_id);if(providerOrderId&&shipmentId){const reconciled=await prisma.shopOrder.update({where:{id:orderId},data:{shiprocketOrderId:providerOrderId,shiprocketShipmentId:shipmentId,shiprocketChannelOrderId:order.orderNumber,shipmentId,shipmentCreatedAt:new Date(),shiprocketIntegrationStatus:"ORDER_CREATED",shiprocketFailureReason:null}});await finishOperation(op.operation.id,true,providerOrderId);return reconciled}}}catch{}}await Promise.all([finishOperation(op.operation.id,false,undefined,error),prisma.shopOrder.update({where:{id:orderId},data:{shiprocketIntegrationStatus:"FAILED",shiprocketFailureReason:error instanceof Error?error.message.slice(0,500):"Order creation failed."}})]);throw error}
}
export async function checkServiceability(orderId:string){
  const config=await getShiprocketConfig();requirePackageConfig(config);const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.deliveryPincode)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Delivery PIN code is missing.");
  const pickupResponse=await shiprocketRequest("/settings/company/pickup",{safeRetry:true}),locations=(Array.isArray(pickupResponse.data)?pickupResponse.data:[]) as Record<string,unknown>[],pickup=locations.find(location=>[location.pickup_location,location.pickup_location_id,location.id].map(string).includes(config.pickupLocation)),pickupPostcode=string(pickup?.pin_code||pickup?.pincode);
  if(!pickupPostcode)throw new ShiprocketError("PICKUP_LOCATION_MISSING","The selected pickup location could not be resolved to a postcode.");
  const query=new URLSearchParams({pickup_postcode:pickupPostcode,delivery_postcode:order.deliveryPincode,cod:"0",weight:String(config.weightKg),declared_value:String(Number(order.totalAmountPaise)/100),mode:config.mode.toLowerCase()});
  const result=await shiprocketRequest(`/courier/serviceability/?${query}`,{safeRetry:true});const available=((result.data as Record<string,unknown>)?.available_courier_companies||[]) as Record<string,unknown>[];
  return available.map(c=>({courierId:string(c.courier_company_id||c.courier_id),courierName:string(c.courier_name),freightCharge:number(c.freight_charge),estimatedDelivery:string(c.etd),rating:number(c.rating),mode:string(c.mode),recommended:Boolean(c.is_recommended),codSupported:Boolean(c.cod)}));
}
export async function assignAwb(orderId:string,courierId:string|undefined,admin?:Admin){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.shiprocketShipmentId)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Create the Shiprocket shipment first.");if(order.awbCode)throw new ShiprocketError("INVALID_SHIPMENT_STATE","AWB is already assigned.");
  const payload={shipment_id:Number(order.shiprocketShipmentId),...(courierId?{courier_id:Number(courierId)}:{})};const op=await beginOperation(orderId,"ASSIGN_AWB",payload);if(op.duplicate)return order;
  try{const response=await shiprocketRequest("/courier/assign/awb",{method:"POST",body:payload});const data=(response.response||response) as Record<string,unknown>,awb=string(data.awb_code||response.awb_code),courierName=string(data.courier_name||response.courier_name);if(!awb)throw new ShiprocketError("AWB_ASSIGNMENT_FAILED","Shiprocket did not return an AWB.",502);const url=`https://shiprocket.co/tracking/${encodeURIComponent(awb)}`;const updated=await prisma.shopOrder.update({where:{id:orderId},data:{awbCode:awb,trackingNumber:awb,courierId:courierId||string(data.courier_company_id)||null,courierName:courierName||null,courierPartner:courierName||null,publicTrackingUrl:url,shipmentStatus:"READY_TO_SHIP",shiprocketIntegrationStatus:"AWB_ASSIGNED",shiprocketFailureReason:null}});await addTrackingEvent(orderId,"AWB_ASSIGNED","Your shipment is booked and awaiting pickup.");await Promise.all([finishOperation(op.operation.id,true,awb),audit(admin,orderId,"SHIPROCKET_AWB_ASSIGNED",{awb,courierId:courierId||null}),notify(orderId,"AWB_ASSIGNED","Your shipment is booked and tracking is now available.")]);return updated}catch(error){await finishOperation(op.operation.id,false,undefined,error);throw error}
}
export async function schedulePickup(orderId:string,pickupDate:string|undefined,admin?:Admin){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.awbCode||!order.shiprocketShipmentId)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Assign an AWB before scheduling pickup.");if(order.pickupScheduledAt)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Pickup is already scheduled.");
  const payload={shipment_id:[Number(order.shiprocketShipmentId)],...(pickupDate?{pickup_date:pickupDate}:{})};const op=await beginOperation(orderId,"SCHEDULE_PICKUP",payload);if(op.duplicate)return order;
  try{const response=await shiprocketRequest("/courier/generate/pickup",{method:"POST",body:payload});const pickupAt=pickupDate?new Date(`${pickupDate}T09:00:00+05:30`):new Date(),token=string(response.pickup_token_number||response.token_number);const updated=await prisma.shopOrder.update({where:{id:orderId},data:{pickupTokenNumber:token||null,pickupScheduledAt:pickupAt,pickupAt,shipmentStatus:"PICKUP_SCHEDULED",shiprocketIntegrationStatus:"PICKUP_SCHEDULED"}});await addTrackingEvent(orderId,"PICKUP_SCHEDULED","Courier pickup has been scheduled.");await Promise.all([finishOperation(op.operation.id,true,token),audit(admin,orderId,"SHIPROCKET_PICKUP_SCHEDULED",{pickupDate:pickupDate||"immediate"}),notify(orderId,"PICKUP_SCHEDULED","Courier pickup has been scheduled.")]);return updated}catch(error){await finishOperation(op.operation.id,false,undefined,error);throw error}
}
export async function generateDocument(orderId:string,type:"LABEL"|"MANIFEST"|"INVOICE",admin?:Admin){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.shiprocketShipmentId||!order.awbCode)throw new ShiprocketError("INVALID_SHIPMENT_STATE","AWB assignment is required.");
  if(type==="MANIFEST"&&!order.pickupScheduledAt)throw new ShiprocketError("INVALID_SHIPMENT_STATE","Schedule pickup before generating a manifest.");
  const path=type==="LABEL"?"/courier/generate/label":type==="MANIFEST"?"/manifests/generate":"/orders/print/invoice";const payload=type==="INVOICE"?{ids:[Number(order.shiprocketOrderId)]}:{shipment_id:[Number(order.shiprocketShipmentId)]};const op=await beginOperation(orderId,`GENERATE_${type}`,payload,operationKey(orderId,`GENERATE_${type}`,randomUUID()));
  try{const response=await shiprocketRequest(path,{method:"POST",body:payload});const url=validUrl(response.label_url||response.manifest_url||response.invoice_url);if(!url)throw new ShiprocketError(`${type}_GENERATION_FAILED`,`Shiprocket did not return a secure ${type.toLowerCase()} URL.`,502);await prisma.shopOrder.update({where:{id:orderId},data:type==="LABEL"?{labelUrl:url}:type==="MANIFEST"?{manifestUrl:url}:{shiprocketInvoiceUrl:url}});await Promise.all([finishOperation(op.operation.id,true,url),audit(admin,orderId,`SHIPROCKET_${type}_GENERATED`,{})]);return url}catch(error){await finishOperation(op.operation.id,false,undefined,error);throw error}
}
async function addTrackingEvent(orderId:string,status:string,message:string,raw?:string){
  const existing=await prisma.shipmentTrackingEvent.findFirst({where:{orderId,status,publicMessage:message},orderBy:{createdAt:"desc"}});
  if(existing&&Date.now()-existing.createdAt.getTime()<60*60_000)return;
  await prisma.shipmentTrackingEvent.create({data:{orderId,status,publicMessage:message,internalNote:raw?`Provider status: ${raw.slice(0,160)}`:null,source:"SHIPROCKET"}});
}
export async function applyTrackingUpdate(orderId:string,rawStatus:string,options:{statusCode?:number;eventAt?:Date;webhook?:boolean}={}){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}}),mapped=mapShiprocketStatus(rawStatus);if(!shouldApplyTracking(order.shipmentStatus,mapped.shipmentStatus))return {applied:false,mapped};
  const orderStatus=mapped.orderStatus&&allowedNextStatuses(order.orderStatus).includes(mapped.orderStatus)?mapped.orderStatus:undefined,now=new Date();
  await prisma.$transaction(async tx=>{await tx.shopOrder.update({where:{id:orderId},data:{shipmentStatus:mapped.shipmentStatus,orderStatus,shiprocketStatusCode:options.statusCode,shiprocketStatusText:rawStatus.slice(0,200),shiprocketRawStatus:rawStatus.slice(0,500),shiprocketIntegrationStatus:mapped.integrationStatus,shiprocketLastSyncedAt:now,shiprocketLastWebhookAt:options.webhook?now:undefined,deliveredAt:mapped.shipmentStatus==="DELIVERED"?(options.eventAt||now):undefined,shiprocketFailureReason:null}});if(orderStatus)await tx.orderStatusHistory.create({data:{orderId,status:orderStatus,publicMessage:mapped.publicMessage,source:"SHIPROCKET"}})});await addTrackingEvent(orderId,mapped.shipmentStatus,mapped.publicMessage,rawStatus);await notify(orderId,mapped.shipmentStatus,mapped.publicMessage);return {applied:true,mapped};
}
export async function refreshTracking(orderId:string){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.awbCode)throw new ShiprocketError("TRACKING_FAILED","Tracking begins after AWB assignment.");
  const response=await shiprocketRequest(`/courier/track/awb/${encodeURIComponent(order.awbCode)}`,{safeRetry:true}),tracking=(response.tracking_data||response) as Record<string,unknown>,status=string(tracking.shipment_status||tracking.current_status||response.status);
  if(!status)throw new ShiprocketError("TRACKING_FAILED","Shiprocket returned no tracking status.",502);return applyTrackingUpdate(orderId,status,{statusCode:number(tracking.shipment_status_id)});
}
export async function cancelShiprocketShipment(orderId:string,admin?:Admin){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.shiprocketOrderId)throw new ShiprocketError("INVALID_SHIPMENT_STATE","No Shiprocket order exists.");if(["PICKUP_SCHEDULED","SHIPPED","IN_TRANSIT","OUT_FOR_DELIVERY","DELIVERED","RETURNED"].includes(order.shipmentStatus))throw new ShiprocketError("INVALID_SHIPMENT_STATE","Shipment cancellation is not permitted after pickup; use the return/RTO workflow.");
  const payload={ids:[Number(order.shiprocketOrderId)]};await shiprocketRequest("/orders/cancel",{method:"POST",body:payload});await prisma.shopOrder.update({where:{id:orderId},data:{shiprocketIntegrationStatus:"CANCELLED",shipmentStatus:"CANCELLED",shiprocketStatusText:"CANCELLED"}});await Promise.all([addTrackingEvent(orderId,"CANCELLED","The shipment was cancelled."),audit(admin,orderId,"SHIPROCKET_SHIPMENT_CANCELLED",{})]);
}
export async function submitNdrAction(orderId:string,action:"REATTEMPT"|"RTO",comments:string,admin:Admin){
  const order=await prisma.shopOrder.findUniqueOrThrow({where:{id:orderId}});if(!order.awbCode)throw new ShiprocketError("INVALID_SHIPMENT_STATE","An AWB is required for NDR action.");const payload={awb:order.awbCode,action:action==="REATTEMPT"?"reattempt":"return",comments:comments.slice(0,500)};await shiprocketRequest("/ndr/action",{method:"POST",body:payload});await audit(admin,orderId,`SHIPROCKET_NDR_${action}`,{commentsLength:comments.length});
}
