import { LegalPage } from "@/components/legal/LegalPage"; import { CONTACT_EMAIL } from "@/lib/footer-config"; import { legalMetadata } from "@/lib/legal-metadata";
export const metadata = legalMetadata("Privacy Policy", "How RateStack handles account, delivery, order and usage information.", "/privacy-policy");
export default function Page() { return <LegalPage title="Privacy Policy" intro="This policy explains the information RateStack uses to provide rates, accounts, direct purchases, delivery, and support.">
  <section><h2>Information collected</h2><p>Depending on the features used, information may include your name, mobile number, email address, Google Sign-In profile information, delivery address, order details, payment status and transaction references, device or browser information, cookies, and session identifiers.</p></section>
  <section><h2>Payments and providers</h2><p>Razorpay and PhonePe may process payments as third-party payment gateways. RateStack receives transaction and verification information needed to fulfil an order, but does not claim to store full payment-card details handled by those gateways.</p></section>
  <section><h2>Use, sharing, and security</h2><p>Information is used for authentication, order fulfilment, fraud prevention, customer support, service improvement, and legal compliance. It may be shared with payment, hosting, analytics, delivery, authentication, and professional service providers only as reasonably necessary. Reasonable technical and organisational safeguards are used, but no online service can promise absolute security.</p></section>
  <section><h2>Retention and rights</h2><p>Records are retained only for operational, legal, accounting, security, and dispute-resolution needs. Subject to applicable law, you may request access, correction, or deletion of eligible personal data.</p></section>
  <section><h2>Contact</h2><p>Send privacy questions or requests to <a href={`mailto:${CONTACT_EMAIL}`} className="text-amber-800 underline">{CONTACT_EMAIL}</a>.</p></section>
</LegalPage>; }
