import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const website=await read("components/shop/ShopCheckout.tsx");
const route=await read("app/(public)/shop/checkout/page.tsx");
const android=await read("android-ratestack/app/src/main/java/com/ratestack/app/ui/shop/NativeShopScreen.kt");
const api=await read("app/api/v1/shop/checkout/route.ts");
test("GST section renders in checkout form before Review Order",()=>assert.ok(website.indexOf("<GstSection")<website.indexOf(">Review Order<")));
test("default selection is No",()=>{assert.match(website,/enabled:false/);assert.match(website,/value="NO" checked=\{!gst\.enabled\}/)});
test("selecting Yes reveals all three required fields",()=>{assert.match(website,/gst\.enabled&&<div data-testid="gst-fields"/);for(const field of ["GST Registered Business Name","GST Number","GST Billing Address"])assert.match(website,new RegExp(field))});
test("selecting No hides conditional GST fields",()=>assert.match(website,/checked=\{!gst\.enabled\} onChange=\{\(\)=>onChange\(\{\.\.\.gst,enabled:false\}\)\}/));
test("same-as-delivery stays synchronized with selected address",()=>{assert.match(website,/effectiveBillingAddress=gst\.sameAsDelivery\?deliveryBillingAddress/);assert.match(website,/value=\{gst\.sameAsDelivery\?delivery:gst\.billingAddress\}/)});
test("invalid GSTIN blocks review with a GST-specific message",()=>assert.match(website,/if \(!gstValid\).*Complete all required GST billing fields/));
test("valid GST details appear in Order Review",()=>{assert.match(website,/review&&gst\.enabled/);assert.match(website,/GST Invoice/)});
test("payment cannot silently continue with missing GST data",()=>assert.match(website,/if\(gst\.enabled&&!gstValid\).*GST billing details are incomplete or invalid/));
test("non-GST checkout sends enabled false",()=>assert.match(website,/:\{enabled:false\}/));
test("current GST selection reaches order-create payload",()=>assert.match(website,/gst:gst\.enabled\?/));
test("server saves immutable order GST snapshot",()=>{assert.match(api,/gstInvoiceRequested/);assert.match(api,/gstBusinessName/);assert.match(api,/gstBillingAddress/)});
test("Android renders default No and conditional GST controls",()=>{assert.match(android,/RadioButton\(!gstEnabled/);assert.match(android,/if\(gstEnabled\)/);assert.match(android,/GstDetailsDto\(true/)});
test("Edit Details does not reset GST state",()=>{assert.doesNotMatch(website,/setGst\([^)]*\).*setReview\(false\)/);assert.doesNotMatch(android,/gstEnabled\s*=\s*false.*review\s*=\s*false/)});
test("production checkout route mounts the GST-enabled component",()=>{assert.match(route,/import \{ ShopCheckout \}/);assert.match(route,/<ShopCheckout\/>/);assert.match(website,/data-testid="gst-billing-section"/)});
