import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import test from "node:test";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
const cases:[string,string,RegExp][]=[
["token registration","app/api/v1/me/devices/route.ts",/upsert/],["token refresh","app/api/v1/me/devices/route.ts",/lastSeenAt/],["token removal on logout","android-ratestack/app/src/main/java/com/ratestack/app/ui/schemes/SchemeViewModel.kt",/revokePushToken/],["multiple devices","prisma/schema.prisma",/PushDeviceToken\[\]/],["invalid token deactivation","lib/notifications/worker.ts",/isActive:false/],["Firebase disabled fallback","lib/notifications/providers.ts",/config\.enabled/],["order event creation","lib/notifications/outbox.ts",/PAYMENT_VERIFIED/],["notification deduplication","prisma/schema.prisma",/deduplicationKey.*@unique/],["notification retry","lib/notifications/worker.ts",/attemptCount/],["deep-link validation","lib/notifications/outbox.ts",/safeDeepLink/],["gold alert","lib/notifications/rate-alerts.ts",/22K gold rate/],["silver alert","lib/notifications/rate-alerts.ts",/Silver rate/],["target threshold","lib/notifications/rate-alerts.ts",/TARGET_AT_OR_BELOW/],["daily duplicate prevention","lib/notifications/rate-alerts.ts",/istDay/],["admin broadcast confirmation","app/admin/(workspace)/notifications/actions.ts",/literal\("CONFIRM"\)/],
["email disabled fallback","lib/notifications/providers.ts",/config\.enabled/],["order confirmation email","lib/notifications/outbox.ts",/ORDER_CONFIRMED/],["payment email","app/api/v1/shop/verify/route.ts",/enqueueOrderEvent/],["invoice template action","lib/notifications/templates.ts",/Download Invoice/],["shipping email","lib/notifications/templates.ts",/Track Order/],["delivery email","lib/notifications/templates.ts",/DELIVERED/],["cancellation email","lib/notifications/outbox.ts",/CANCELLED/],["refund email","lib/notifications/outbox.ts",/REFUNDED/],["email duplicate prevention","lib/notifications/outbox.ts",/upsert/],["email retry handling","lib/notifications/worker.ts",/2\*\*current/],["template escaping","lib/notifications/templates.ts",/replace\(/],["customer-data protection","lib/notifications/templates.ts",/escape\(order\.customerName\)/],["admin resend permission","lib/admin-permissions.ts",/EMAIL_RESEND/],
["sales totals","lib/reports/service.ts",/grossSales/],["GST calculation","lib/reports/service.ts",/gstPaise/],["refund adjustment","lib/reports/service.ts",/netSales=grossSales-refundAmount/],["revenue calculation","lib/reports/service.ts",/netSalesPaise/],["profit calculation","lib/reports/service.ts",/estimatedProfitPaise/],["missing-cost warning","lib/reports/service.ts",/missingCostWarning/],["gold analytics","lib/reports/service.ts",/gold:metal/],["silver analytics","lib/reports/service.ts",/silver:metal/],["courier success rate","lib/reports/service.ts",/deliverySuccessRate/],["RTO calculation","lib/reports/service.ts",/rtoRate/],["date filtering","lib/reports/service.ts",/reportRange/],["timezone handling","lib/reports/service.ts",/\+05:30/],["admin permission restrictions","lib/admin-permissions.ts",/PROFIT_VIEW/],["CSV export","app/api/v1/admin/reports/export/route.ts",/text\/csv/],["empty reports","lib/reports/service.ts",/paid\.length\?/],["large-range validation","lib/reports/service.ts",/REPORT_RANGE_TOO_LARGE/],["audit-log creation","app/api/v1/admin/reports/export/route.ts",/REPORT_EXPORTED/],
["Android FCM sync","android-ratestack/app/src/main/java/com/ratestack/app/FcmTokenSync.kt",/registerPushDevice/],["Android push deep links","android-ratestack/app/src/main/java/com/ratestack/app/UrlPolicy.kt",/NavigationDestination\.INTERNAL/],["Android permission handling","android-ratestack/app/src/main/java/com/ratestack/app/MainActivity.kt",/POST_NOTIFICATIONS/],["Android rate-alert settings","android-ratestack/app/src/main/java/com/ratestack/app/ui/shop/MyOrdersScreen.kt",/Gold rate alerts/],["Android order settings","android-ratestack/app/src/main/java/com/ratestack/app/ui/shop/MyOrdersScreen.kt",/Order notifications/],["foreground notification handling","android-ratestack/app/src/main/java/com/ratestack/app/RateStackMessagingService.kt",/onMessageReceived/],
];
for(const [name,path,pattern] of cases)test(name,async()=>assert.match(await read(path),pattern));
