"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useState, useSyncExternalStore } from "react";
import { AuthModal } from "@/components/AuthModal";
import { NotificationPreferences } from "@/components/customer/NotificationPreferences";

type Address = { id?:string;fullName:string;mobile:string;addressLine1:string;addressLine2:string;landmark:string;city:string;district:string;state:string;pincode:string;country:"India";addressType:"HOME"|"OFFICE"|"OTHER";isDefault?:boolean };
type Order = { id:string;orderNumber:string;productId:string;productName:string;imageUrl:string|null;metalType:string;purity:string;weightGrams:number;quantity:number;metalValue:number;serviceCharge:number;gst:number;shipping:number;total:number;gateway:string;paymentStatus:string;orderStatus:string;paymentId:string|null;invoiceNumber:string|null;createdAt:string;deliveryAddress:Address|null;shipment:{courierPartner:string|null;trackingNumber:string|null;status:string;pickupStatus:string;expectedDelivery:string|null;deliveredAt:string|null;lastUpdated:string|null;timeline:Array<{label:string;at:string}>;trackingUrl:string|null;message:string|null} };
type GstProfile={id:string;businessName:string;gstNumber:string;billingAddress:string;isActive:boolean};
type Dashboard = { customer:{fullName:string;phone:string|null;email:string|null;emailVerified:boolean;mobileVerified:boolean;googleConnected:boolean;memberSince:string};summary:{totalOrders:number;paidOrders:number;activeShipments:number;totalSpent:number};orders:Order[];addresses:Address[];gstProfile:GstProfile|null;paymentHistory:Array<{orderNumber:string;gateway:string;paymentId:string|null;status:string;amount:number;date:string}>;rewards:{points:number;tier:string;message:string};notifications:Array<{id:string;title:string;date:string}>;wishlist:unknown[] };
const blank:Address={fullName:"",mobile:"",addressLine1:"",addressLine2:"",landmark:"",city:"",district:"",state:"",pincode:"",country:"India",addressType:"HOME"};
const card="rounded-3xl border border-amber-300/15 bg-white/[0.055] p-5 shadow-[0_18px_60px_rgba(0,0,0,.28)] backdrop-blur-xl sm:p-6";
const readToken=()=>localStorage.getItem("scheme_user_token")||localStorage.getItem("ratestack_user_token")||"";
const readRequestedOrderId=()=>new URLSearchParams(window.location.search).get("orderId")||"";
const subscribeToLocation=()=>()=>{};
const subscribeToAuth=(onChange:()=>void)=>{window.addEventListener("auth:change",onChange);window.addEventListener("storage",onChange);return()=>{window.removeEventListener("auth:change",onChange);window.removeEventListener("storage",onChange);};};

export function CustomerDashboard(){
  const [data,setData]=useState<Dashboard|null>(null); const [login,setLogin]=useState(false); const [error,setError]=useState(""); const [address,setAddress]=useState<Address|null>(null);
  const token=useSyncExternalStore(subscribeToAuth,readToken,()=>"");
  const requestedOrderId=useSyncExternalStore(subscribeToLocation,readRequestedOrderId,()=>"");
  const load=useCallback(()=>{if(!token)return;fetch("/api/v1/me/dashboard",{headers:{Authorization:`Bearer ${token}`},cache:"no-store"}).then(r=>r.json()).then(b=>{if(!b.success)throw new Error(b.error?.message);setData(b.data)}).catch(e=>setError(e.message||"Dashboard unavailable."));},[token]);
  useEffect(()=>{void load();},[load]);
  async function saveAddress(){if(!address)return;const method=address.id?"PUT":"POST";const url=address.id?`/api/v1/me/addresses/${address.id}`:"/api/v1/me/addresses";const r=await fetch(url,{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify(address)});const b=await r.json();if(!r.ok){setError(b.error?.message);return;}setAddress(null);load();}
  async function addressAction(id:string,action:"delete"|"default"){const r=await fetch(`/api/v1/me/addresses/${id}${action==="default"?"/default":""}`,{method:action==="delete"?"DELETE":"POST",headers:{Authorization:`Bearer ${token}`}});const b=await r.json();if(!r.ok){setError(b.error?.message);return;}load();}
  async function invoice(order:Order){const r=await fetch(`/api/v1/me/orders/${order.id}/invoice`,{headers:{Authorization:`Bearer ${token}`}});if(!r.ok){setError("Invoice unavailable.");return;}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`${order.invoiceNumber||order.orderNumber}.html`;a.click();URL.revokeObjectURL(url);}
  async function refreshTracking(order:Order){setError("");const r=await fetch(`/api/v1/me/orders/${order.id}/tracking`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const body=await r.json();if(!r.ok){setError(body.error?.message||"Tracking is temporarily unavailable.");return;}load();}
  function logout(){["scheme_user_token","ratestack_user_token","scheme_user_name","scheme_user_phone"].forEach(key=>localStorage.removeItem(key));window.dispatchEvent(new CustomEvent("auth:change"));window.location.href="/";}
  if(!data)return <main className="mx-auto min-h-[70vh] max-w-7xl px-4 py-20 text-center"><p>{error||(!token?"Sign in to open your Dashboard.":"Loading your Dashboard…")}</p>{!token&&!login&&<button onClick={()=>setLogin(true)} className="mt-5 rounded-xl bg-amber-400 px-5 py-3 font-black text-stone-950">Login to Dashboard</button>}{login&&<AuthModal initialMode="login" redirectTo="/shop/orders" onClose={()=>setLogin(false)} onSuccess={()=>{setLogin(false);load();}}/>}</main>;
  const requested=data.orders.find(order=>order.id===requestedOrderId);
  const recent=requested?[requested,...data.orders.filter(order=>order.id!==requested.id).slice(0,2)]:data.orders.slice(0,3);
  const tracked=requested||data.orders.find(order=>order.shipment.trackingNumber)||data.orders[0];
  return <main className="relative overflow-hidden"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_top_left,rgba(217,160,49,.18),transparent_32%),radial-gradient(circle_at_90%_25%,rgba(255,255,255,.06),transparent_25%)]"/><div className="relative mx-auto max-w-7xl space-y-6 px-4 py-10 sm:px-6 lg:px-8">
    <section className={`${card} overflow-hidden bg-gradient-to-br from-amber-300/15 via-white/[.06] to-transparent`}><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-[.24em] text-amber-300">My Dashboard</p><h1 className="mt-3 font-display text-4xl font-bold sm:text-5xl">Welcome, {data.customer.fullName}</h1><p className="mt-2 text-stone-400">Your orders, deliveries, addresses and account—beautifully organised in one place.</p></div><button onClick={logout} className="rounded-xl border border-red-300/30 px-5 py-3 font-bold text-red-200 hover:bg-red-400/10">Logout</button></div></section>
    <section aria-labelledby="orders-summary-title"><h2 id="orders-summary-title" className="mb-4 font-display text-2xl font-bold">Orders Summary</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Total Orders",data.summary.totalOrders],["Paid Orders",data.summary.paidOrders],["Live Shipments",data.summary.activeShipments],["Total Spent",`₹${data.summary.totalSpent.toLocaleString("en-IN")}`]].map(([label,value])=><article key={label} className={card}><p className="text-xs font-black uppercase tracking-wider text-stone-500">{label}</p><p className="mt-3 text-3xl font-black text-amber-300">{value}</p></article>)}</div></section>
    <section className="grid gap-6 lg:grid-cols-2"><DashboardCard title="Customer Information"><p className="text-xl font-black">{data.customer.fullName}</p><p>{data.customer.phone||"Mobile not added"} · {data.customer.mobileVerified?"Verified":"Not verified"}</p><p>{data.customer.email||"Email not added"} · {data.customer.emailVerified?"Verified":"Not verified"}</p><p className="text-sm text-stone-500">Member since {new Date(data.customer.memberSince).toLocaleDateString("en-IN")}</p></DashboardCard><DashboardCard title="Account Settings"><p>Google Sign-In: <b>{data.customer.googleConnected?"Connected":"Not connected"}</b></p><p>Communication preferences and customer information are managed securely from this Dashboard.</p><Link href="/contact-us" className="text-amber-300">Request an account update →</Link></DashboardCard></section>
    <DashboardCard title="Recent Orders">{recent.length?recent.map(order=><OrderCard key={order.id} order={order} onInvoice={invoice}/>):<Empty text="No orders yet."/>}</DashboardCard>
    <section className="grid gap-6 lg:grid-cols-2"><DashboardCard title="Live Order Tracking">{tracked?<Shipment order={tracked}/>:<Empty text="Tracking begins after your first order is dispatched."/>}</DashboardCard><DashboardCard title="Shipment Details"><p className="text-stone-300">Courier Partner: <b>{tracked?.shipment.courierPartner||"Assignment pending"}</b></p><p>AWB: <b>{tracked?.shipment.trackingNumber||"Not assigned"}</b></p><p>Shipment Status: <b>{tracked?.shipment.status||"No shipment"}</b></p><p>Pickup Status: <b>{tracked?.shipment.pickupStatus||"Not scheduled"}</b></p><p>Expected Delivery: <b>{tracked?.shipment.expectedDelivery?new Date(tracked.shipment.expectedDelivery).toLocaleDateString("en-IN"):"To be confirmed"}</b></p><p>Delivered: <b>{tracked?.shipment.deliveredAt?new Date(tracked.shipment.deliveredAt).toLocaleDateString("en-IN"):"—"}</b></p><p className="text-xs text-stone-500">Last updated: {tracked?.shipment.lastUpdated?new Date(tracked.shipment.lastUpdated).toLocaleString("en-IN"):"—"}</p>{tracked?.shipment.message&&<p className="rounded-xl bg-white/5 p-3 text-sm">{tracked.shipment.message}</p>}<div className="flex flex-wrap gap-2">{tracked?.shipment.trackingNumber&&<button onClick={()=>refreshTracking(tracked)} className="rounded-xl border px-4 py-2 font-bold">Refresh Tracking</button>}{tracked?.shipment.trackingUrl&&<a href={tracked.shipment.trackingUrl} target="_blank" rel="noreferrer" className="inline-block rounded-xl bg-amber-400 px-4 py-2 font-black text-stone-950">Track Shipment</a>}</div></DashboardCard></section>
    <DashboardCard title="Saved Addresses"><div className="mb-4 flex justify-end"><button onClick={()=>setAddress({...blank,fullName:data.customer.fullName,mobile:data.customer.phone||""})} className="rounded-xl bg-amber-400 px-4 py-2 font-black text-stone-950">Add Address</button></div><div className="grid gap-4 md:grid-cols-2">{data.addresses.map(item=><article key={item.id} className="rounded-2xl border border-white/10 bg-black/20 p-4"><div className="flex justify-between"><b>{item.fullName}</b>{item.isDefault&&<span className="rounded-full bg-emerald-400/15 px-2 py-1 text-xs font-black text-emerald-300">Default Address</span>}</div><p className="mt-2 text-sm text-stone-300">{item.mobile}<br/>{item.addressLine1}{item.addressLine2?`, ${item.addressLine2}`:""}<br/>{item.city}, {item.district}, {item.state} – {item.pincode}</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setAddress(item)} className="text-xs font-bold text-amber-300">Edit</button><button onClick={()=>addressAction(item.id!,"delete")} disabled={data.addresses.length===1} className="text-xs font-bold text-red-300 disabled:opacity-40">Delete</button>{!item.isDefault&&<button onClick={()=>addressAction(item.id!,"default")} className="text-xs font-bold text-emerald-300">Set Default</button>}</div></article>)}</div></DashboardCard>
    <GstProfileManager initial={data.gstProfile} token={token} onChanged={load}/>
    <NotificationPreferences token={token}/>
    {address&&<AddressEditor value={address} onChange={setAddress} onSave={saveAddress} onClose={()=>setAddress(null)}/>}
    <section className="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><DashboardCard title="Security"><p>Password, verified mobile/email and Google Sign-In protect your account.</p><p className="text-emerald-300">Server-verified payments and owner-only data access enabled.</p></DashboardCard><DashboardCard title="Reward Points"><p className="text-4xl font-black text-amber-300">{data.rewards.points}</p><p>{data.rewards.tier} tier</p><p className="text-sm text-stone-500">{data.rewards.message}</p></DashboardCard><DashboardCard title="Notifications">{data.notifications.length?data.notifications.map(n=><p key={n.id} className="border-b border-white/10 py-2 text-sm">{n.title}<br/><span className="text-stone-500">{new Date(n.date).toLocaleDateString("en-IN")}</span></p>):<Empty text="No new notifications."/>}</DashboardCard></section>
    <section className="grid gap-6 lg:grid-cols-2"><DashboardCard title="Download Invoices">{data.orders.filter(o=>o.invoiceNumber).map(order=><button key={order.id} onClick={()=>invoice(order)} className="flex w-full justify-between border-b border-white/10 py-3 text-left"><span>{order.invoiceNumber}<br/><small>{order.productName}</small></span><b className="text-amber-300">Download</b></button>)}{!data.orders.some(o=>o.invoiceNumber)&&<Empty text="Invoices appear after successful payment."/>}</DashboardCard><DashboardCard title="Payment History">{data.paymentHistory.map(payment=><div key={payment.orderNumber} className="flex justify-between border-b border-white/10 py-3 text-sm"><span>{payment.orderNumber}<br/><small>{payment.gateway} · {payment.status}</small></span><b>₹{payment.amount.toLocaleString("en-IN")}</b></div>)}</DashboardCard></section>
    <section className="grid gap-6 md:grid-cols-2 lg:grid-cols-3"><DashboardCard title="Wishlist"><Empty text="Your wishlist is ready for future favourite products."/></DashboardCard><DashboardCard title="Support Center"><p>Need help with an order, payment, invoice or delivery?</p><Link href="/contact-us" className="text-amber-300">Contact RateStack Support →</Link></DashboardCard><DashboardCard title="Quick Actions"><div className="grid gap-2"><Link href="/shop" className="rounded-xl bg-amber-400 p-3 text-center font-black text-stone-950">Shop Coins</Link><Link href="/#rates" className="rounded-xl border border-amber-300/30 p-3 text-center font-bold">Today’s Rates</Link><Link href="/#calculator" className="rounded-xl border border-white/10 p-3 text-center font-bold">Calculator</Link></div></DashboardCard></section>
  </div></main>;
}
function GstProfileManager({initial,token,onChanged}:{initial:GstProfile|null;token:string;onChanged:()=>void}){const [editing,setEditing]=useState(!initial);const [value,setValue]=useState({businessName:initial?.businessName||"",gstNumber:initial?.gstNumber||"",billingAddress:initial?.billingAddress||""});const [message,setMessage]=useState("");async function save(){const response=await fetch("/api/v1/me/gst-profile",{method:"PUT",headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:JSON.stringify({...value,enabled:true,gstNumber:value.gstNumber.trim().toUpperCase()})});const body=await response.json();if(!response.ok){setMessage(body.error?.message||"Unable to save GST details.");return}setEditing(false);setMessage("");onChanged()}async function action(method:"PATCH"|"DELETE"){await fetch("/api/v1/me/gst-profile",{method,headers:{"Content-Type":"application/json",Authorization:`Bearer ${token}`},body:method==="PATCH"?JSON.stringify({isActive:!initial?.isActive}):undefined});onChanged()}return <DashboardCard title="My GST Details">{initial&&!editing?<><p className="text-xl font-black">{initial.businessName}</p><p>GSTIN: {initial.gstNumber}</p><p className="whitespace-pre-line text-sm text-stone-300">{initial.billingAddress}</p><p className={initial.isActive?"text-emerald-300":"text-stone-500"}>{initial.isActive?"Enabled":"Disabled"}</p><div className="flex gap-3"><button onClick={()=>setEditing(true)} className="text-amber-300">Edit</button><button onClick={()=>action("PATCH")} className="text-amber-300">{initial.isActive?"Disable":"Enable"}</button><button onClick={()=>action("DELETE")} className="text-red-300">Delete</button></div></>:<div className="grid gap-3"><input value={value.businessName} maxLength={150} onChange={event=>setValue({...value,businessName:event.target.value})} placeholder="GST Registered Business Name" className="rounded-xl border border-white/10 bg-black/20 p-3"/><textarea value={value.billingAddress} maxLength={500} onChange={event=>setValue({...value,billingAddress:event.target.value})} placeholder="GST Billing Address" className="rounded-xl border border-white/10 bg-black/20 p-3"/><input value={value.gstNumber} maxLength={15} onChange={event=>setValue({...value,gstNumber:event.target.value.trim().toUpperCase()})} placeholder="GST Number" className="rounded-xl border border-white/10 bg-black/20 p-3"/>{message&&<p className="text-red-300">{message}</p>}<button onClick={save} className="rounded-xl bg-amber-400 p-3 font-black text-stone-950">Save GST Details</button></div>}</DashboardCard>}
function DashboardCard({title,children}:{title:string;children:React.ReactNode}){return <section className={card}><h2 className="mb-4 font-display text-2xl font-bold text-amber-200">{title}</h2><div className="space-y-2 text-stone-300">{children}</div></section>}
function Empty({text}:{text:string}){return <p className="py-5 text-center text-stone-500">{text}</p>}
function Shipment({order}:{order:Order}){return <div><p className="font-black">{order.orderNumber} · {order.shipment.status}</p><div className="mt-4 border-l border-amber-400/40 pl-5">{order.shipment.timeline.map((event,index)=><div key={`${event.label}-${index}`} className="relative pb-5"><span className="absolute -left-[1.45rem] top-1 h-2 w-2 rounded-full bg-amber-300"/><b>{event.label}</b><p className="text-xs text-stone-500">{new Date(event.at).toLocaleString("en-IN")}</p></div>)}</div></div>}
function OrderCard({order,onInvoice}:{order:Order;onInvoice:(order:Order)=>void}){return <article className="mb-4 grid gap-4 rounded-2xl border border-white/10 bg-black/20 p-4 md:grid-cols-[120px_1fr]"><div className="relative h-28 overflow-hidden rounded-xl bg-white">{order.imageUrl&&<Image src={order.imageUrl} alt={order.productName} fill className="object-contain p-2"/>}</div><div><div className="flex justify-between gap-3"><div><h3 className="text-lg font-black text-white">{order.productName}</h3><p className="text-sm">{order.purity} · {order.weightGrams}g × {order.quantity}</p></div><b className="text-amber-300">₹{order.total.toLocaleString("en-IN")}</b></div><div className="mt-3 grid gap-1 text-xs sm:grid-cols-2"><p><span>Metal Value</span>: ₹{order.metalValue.toLocaleString("en-IN")}</p><p><span>Service Charge</span>: ₹{order.serviceCharge.toLocaleString("en-IN")}</p><p><span>GST (3%)</span>: ₹{order.gst.toLocaleString("en-IN")}</p><p><span>Shipping Cost</span>: {order.shipping===0?"FREE":`₹${order.shipping}`}</p><p><span>Total Payable</span>: ₹{order.total.toLocaleString("en-IN")}</p><p>Payment: {order.paymentStatus}</p><p>Shipment: {order.shipment.status}</p></div>{order.deliveryAddress&&<p className="mt-3 text-xs text-stone-400">Deliver to: {order.deliveryAddress.addressLine1}, {order.deliveryAddress.city} – {order.deliveryAddress.pincode}</p>}<div className="mt-3 flex flex-wrap gap-2">{order.invoiceNumber&&<button onClick={()=>onInvoice(order)} className="rounded-lg border border-amber-300/30 px-3 py-2 text-xs font-bold">Invoice</button>}<Link href={`/shop?buyAgain=${order.productId}`} className="rounded-lg bg-amber-400 px-3 py-2 text-xs font-black text-stone-950">Buy Again</Link><Link href="/contact-us" className="rounded-lg border border-white/10 px-3 py-2 text-xs font-bold">Need Help</Link></div></div></article>}
function AddressEditor({value,onChange,onSave,onClose}:{value:Address;onChange:(value:Address)=>void;onSave:()=>void;onClose:()=>void}){const field=(key:keyof Address,label:string)=><label className="text-xs font-bold">{label}<input value={String(value[key]??"")} onChange={e=>onChange({...value,[key]:e.target.value})} className="mt-1 w-full rounded-xl border border-white/10 bg-black/30 p-3"/></label>;return <div className={`${card} fixed inset-x-4 bottom-4 z-[60] mx-auto max-h-[85vh] max-w-2xl overflow-auto bg-stone-950`}><div className="flex justify-between"><h2 className="text-xl font-black">Address</h2><button onClick={onClose}>Close</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{field("fullName","Full Name")}{field("mobile","Mobile")}{field("addressLine1","Address Line 1")}{field("addressLine2","Address Line 2")}{field("landmark","Landmark")}{field("city","City")}{field("district","District")}{field("state","State")}{field("pincode","PIN Code")}</div><button onClick={onSave} className="mt-4 w-full rounded-xl bg-amber-400 p-3 font-black text-stone-950">Save Address</button></div>}
