import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { authenticateSchemeUserFromRequest } from "@/lib/schemes/user-auth";
import { gstDetailsSchema } from "@/lib/gst";
export const dynamic="force-dynamic";
export async function GET(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return NextResponse.json({success:false,error:{message:"Authentication required."}},{status:401});const profile=await prisma.customerGSTProfile.findFirst({where:{customerId:auth.userId,isDefault:true},orderBy:{updatedAt:"desc"}});return NextResponse.json({success:true,data:profile},{headers:{"Cache-Control":"private, no-store"}})}
export async function PUT(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return NextResponse.json({success:false,error:{message:"Authentication required."}},{status:401});const parsed=gstDetailsSchema.safeParse({...await request.json().catch(()=>null),enabled:true});if(!parsed.success)return NextResponse.json({success:false,error:{code:"INVALID_GST_DETAILS",message:parsed.error.issues[0]?.message}},{status:400});const current=await prisma.customerGSTProfile.findFirst({where:{customerId:auth.userId,isDefault:true}});const data={businessName:parsed.data.businessName,gstNumber:parsed.data.gstNumber,billingAddress:parsed.data.billingAddress,isActive:true,isDefault:true};const profile=current?await prisma.customerGSTProfile.update({where:{id:current.id},data}):await prisma.customerGSTProfile.create({data:{customerId:auth.userId,...data}});await prisma.auditLog.create({data:{actorType:"CUSTOMER",actorId:auth.userId,action:"GST_PROFILE_UPDATED",targetEntity:"CustomerGSTProfile",targetId:profile.id,detailsJson:{enabled:true,gstLastFour:profile.gstNumber.slice(-4)}}});return NextResponse.json({success:true,data:profile})}
export async function DELETE(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return NextResponse.json({success:false,error:{message:"Authentication required."}},{status:401});const current=await prisma.customerGSTProfile.findFirst({where:{customerId:auth.userId,isDefault:true}});if(current){await prisma.$transaction([prisma.customerGSTProfile.delete({where:{id:current.id}}),prisma.auditLog.create({data:{actorType:"CUSTOMER",actorId:auth.userId,action:"GST_PROFILE_DELETED",targetEntity:"CustomerGSTProfile",targetId:current.id,detailsJson:{gstLastFour:current.gstNumber.slice(-4)}}})])}return NextResponse.json({success:true,data:{deleted:Boolean(current)}})}
export async function PATCH(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return NextResponse.json({success:false,error:{message:"Authentication required."}},{status:401});const body=await request.json().catch(()=>null),isActive=body?.isActive;if(typeof isActive!=="boolean")return NextResponse.json({success:false,error:{message:"Invalid status."}},{status:400});const current=await prisma.customerGSTProfile.findFirst({where:{customerId:auth.userId,isDefault:true}});if(!current)return NextResponse.json({success:false,error:{message:"GST profile not found."}},{status:404});const profile=await prisma.customerGSTProfile.update({where:{id:current.id},data:{isActive}});await prisma.auditLog.create({data:{actorType:"CUSTOMER",actorId:auth.userId,action:isActive?"GST_PROFILE_ENABLED":"GST_PROFILE_DISABLED",targetEntity:"CustomerGSTProfile",targetId:profile.id,detailsJson:{gstLastFour:profile.gstNumber.slice(-4)}}});return NextResponse.json({success:true,data:profile})}
