CREATE TYPE "ShiprocketIntegrationStatus" AS ENUM ('DISABLED','NOT_CONFIGURED','READY','ORDER_CREATED','AWB_ASSIGNED','PICKUP_SCHEDULED','IN_TRANSIT','DELIVERED','CANCELLED','RTO','FAILED','MANUAL');
CREATE TYPE "LogisticsOperationStatus" AS ENUM ('PENDING','SUCCESS','FAILED');
CREATE TYPE "LogisticsWebhookStatus" AS ENUM ('RECEIVED','PROCESSED','FAILED','IGNORED');
CREATE TYPE "NotificationOutboxStatus" AS ENUM ('PENDING','SENT','FAILED');
ALTER TABLE "ShopOrder" ADD COLUMN "shiprocketChannelOrderId" TEXT, ADD COLUMN "shiprocketStatusCode" INTEGER, ADD COLUMN "shiprocketStatusText" TEXT, ADD COLUMN "courierId" TEXT, ADD COLUMN "courierName" TEXT, ADD COLUMN "awbCode" TEXT, ADD COLUMN "pickupTokenNumber" TEXT, ADD COLUMN "pickupScheduledAt" TIMESTAMP(3), ADD COLUMN "pickupExpectedAt" TIMESTAMP(3), ADD COLUMN "shipmentCreatedAt" TIMESTAMP(3), ADD COLUMN "labelUrl" TEXT, ADD COLUMN "manifestUrl" TEXT, ADD COLUMN "shiprocketInvoiceUrl" TEXT, ADD COLUMN "estimatedDeliveryAt" TIMESTAMP(3), ADD COLUMN "shiprocketLastSyncedAt" TIMESTAMP(3), ADD COLUMN "shiprocketLastWebhookAt" TIMESTAMP(3), ADD COLUMN "shiprocketRawStatus" TEXT, ADD COLUMN "shiprocketIntegrationStatus" "ShiprocketIntegrationStatus" NOT NULL DEFAULT 'DISABLED', ADD COLUMN "shiprocketFailureReason" TEXT;
CREATE TABLE "ShiprocketOperation" ("id" TEXT NOT NULL,"shopOrderId" TEXT NOT NULL,"operationType" TEXT NOT NULL,"idempotencyKey" TEXT NOT NULL,"requestFingerprint" TEXT NOT NULL,"status" "LogisticsOperationStatus" NOT NULL DEFAULT 'PENDING',"responseReference" TEXT,"errorCode" TEXT,"errorMessage" TEXT,"attemptedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"retryCount" INTEGER NOT NULL DEFAULT 0,CONSTRAINT "ShiprocketOperation_pkey" PRIMARY KEY ("id"));
CREATE TABLE "LogisticsWebhookEvent" ("id" TEXT NOT NULL,"provider" TEXT NOT NULL,"eventIdentifier" TEXT,"awb" TEXT,"shipmentId" TEXT,"statusText" TEXT,"eventOccurredAt" TIMESTAMP(3),"payloadHash" TEXT NOT NULL,"payloadJson" JSONB NOT NULL,"receivedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"processedAt" TIMESTAMP(3),"processingStatus" "LogisticsWebhookStatus" NOT NULL DEFAULT 'RECEIVED',"failureReason" TEXT,"shopOrderId" TEXT,CONSTRAINT "LogisticsWebhookEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "NotificationOutbox" ("id" TEXT NOT NULL,"shopOrderId" TEXT NOT NULL,"eventType" TEXT NOT NULL,"title" TEXT NOT NULL,"body" TEXT NOT NULL,"payloadJson" JSONB,"status" "NotificationOutboxStatus" NOT NULL DEFAULT 'PENDING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"sentAt" TIMESTAMP(3),"lastError" TEXT,CONSTRAINT "NotificationOutbox_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ShopOrder_awbCode_key" ON "ShopOrder"("awbCode");
CREATE INDEX "ShopOrder_shiprocketShipmentId_idx" ON "ShopOrder"("shiprocketShipmentId");
CREATE INDEX "ShopOrder_shiprocketIntegrationStatus_shiprocketLastSyncedAt_idx" ON "ShopOrder"("shiprocketIntegrationStatus","shiprocketLastSyncedAt");
CREATE UNIQUE INDEX "ShiprocketOperation_idempotencyKey_key" ON "ShiprocketOperation"("idempotencyKey");
CREATE INDEX "ShiprocketOperation_shopOrderId_operationType_idx" ON "ShiprocketOperation"("shopOrderId","operationType");
CREATE INDEX "ShiprocketOperation_status_attemptedAt_idx" ON "ShiprocketOperation"("status","attemptedAt");
CREATE UNIQUE INDEX "LogisticsWebhookEvent_payloadHash_key" ON "LogisticsWebhookEvent"("payloadHash");
CREATE UNIQUE INDEX "LogisticsWebhookEvent_provider_eventIdentifier_key" ON "LogisticsWebhookEvent"("provider","eventIdentifier");
CREATE INDEX "LogisticsWebhookEvent_processingStatus_receivedAt_idx" ON "LogisticsWebhookEvent"("processingStatus","receivedAt");
CREATE INDEX "LogisticsWebhookEvent_awb_idx" ON "LogisticsWebhookEvent"("awb");
CREATE INDEX "LogisticsWebhookEvent_shipmentId_idx" ON "LogisticsWebhookEvent"("shipmentId");
CREATE INDEX "NotificationOutbox_status_createdAt_idx" ON "NotificationOutbox"("status","createdAt");
CREATE INDEX "NotificationOutbox_shopOrderId_createdAt_idx" ON "NotificationOutbox"("shopOrderId","createdAt");
ALTER TABLE "ShiprocketOperation" ADD CONSTRAINT "ShiprocketOperation_shopOrderId_fkey" FOREIGN KEY ("shopOrderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "LogisticsWebhookEvent" ADD CONSTRAINT "LogisticsWebhookEvent_shopOrderId_fkey" FOREIGN KEY ("shopOrderId") REFERENCES "ShopOrder"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "NotificationOutbox" ADD CONSTRAINT "NotificationOutbox_shopOrderId_fkey" FOREIGN KEY ("shopOrderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
