import Link from "next/link";
import { requireCustomerAdmin } from "@/lib/customer-admin";
import { filteredCoverage, latestCoverageReport, type CoverageFilters, type SupportedRow, type UnsupportedRow, type FailedRow } from "@/lib/goodreturns-coverage";

export const dynamic = "force-dynamic";
const cell = "px-4 py-3 align-top";
const query = (filters: CoverageFilters, changes: Record<string,string>) => new URLSearchParams({...filters,...changes} as Record<string,string>).toString();

export default async function GoodReturnsCitiesPage({searchParams}:{searchParams:Promise<CoverageFilters>}) {
  await requireCustomerAdmin("REPORTS_VIEW");
  const filters=await searchParams, report=await latestCoverageReport();
  if(!report)return <div><h1 className="font-display text-4xl font-bold">GoodReturns City Coverage</h1><p className="mt-2 text-stone-600">View the latest verified GoodReturns catalogue coverage for RateStack cities.</p><div className="mt-8 rounded-2xl border bg-white p-10 text-center"><p>No successful GoodReturns catalogue report is available yet. Run Rate Sync from API Logs first.</p><Link href="/admin/api-logs" className="mt-5 inline-block rounded-xl bg-stone-950 px-5 py-3 font-bold text-amber-300">Open API Logs</Link></div></div>;
  const result=filteredCoverage(report,filters), pages=Math.max(1,Math.ceil(result.total/result.size));
  const supported=result.rows as SupportedRow[], unsupported=result.rows as UnsupportedRow[], failed=result.rows as FailedRow[];
  return <div className="space-y-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Rates</p><h1 className="font-display text-4xl font-bold">GoodReturns City Coverage</h1><p className="mt-2 text-stone-600">View the latest verified GoodReturns catalogue coverage for RateStack cities.</p><p className="mt-2 text-sm text-stone-500">Latest sync: {report.createdAt.toLocaleString("en-IN",{timeZone:"Asia/Kolkata"})} IST · Source: GoodReturns · Report status: {report.status}</p></div><Link href="/admin/api-logs" className="rounded-xl border bg-white px-5 py-3 font-bold">Open API Logs</Link></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{Object.entries({"Total Active Cities":report.totalActiveCities,"Supported Cities":report.supported,"Unsupported Cities":report.unsupported,"Alias Cities":report.aliases,"Failed Cities":report.failed,"Last Catalogue Sync":report.createdAt.toLocaleDateString("en-IN",{timeZone:"Asia/Kolkata"})}).map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-stone-500">{label}</p><p className="mt-2 text-2xl font-black">{value}</p></article>)}</section>
    <p className="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Unsupported cities are not assigned another city&apos;s rate. No Trichy or cross-city fallback is used.</p>
    <nav className="flex flex-wrap gap-2" aria-label="Coverage tabs">{[["supported","Supported Cities"],["unsupported","Unsupported Cities"],["failed","Failed Cities"]].map(([tab,label])=><Link key={tab} href={`?${query(filters,{tab,page:"1"})}`} className={`rounded-full px-4 py-2 text-sm font-bold ${result.tab===tab?"bg-stone-950 text-amber-300":"border bg-white"}`}>{label}</Link>)}</nav>
    <form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3 xl:grid-cols-6"><input type="hidden" name="tab" value={result.tab}/><input name="q" defaultValue={filters.q} placeholder="City, provider city or state" className="rounded-xl border p-3 xl:col-span-2"/><select name="state" defaultValue={filters.state||""} className="rounded-xl border p-3"><option value="">All states</option>{result.states.map(state=><option key={state}>{state}</option>)}</select>{result.tab==="supported"&&<select name="mapping" defaultValue={filters.mapping||"all"} className="rounded-xl border p-3"><option value="all">All mappings</option><option value="exact">Exact</option><option value="alias">Alias</option></select>}<select name="sort" defaultValue={filters.sort||"state"} className="rounded-xl border p-3"><option value="state">Sort: State</option><option value="city">Sort: City</option>{result.tab!=="unsupported"&&<option value="slug">Sort: Provider Slug</option>}{result.tab==="supported"&&<option value="mapping">Sort: Mapping Type</option>}</select><select name="size" defaultValue={String(result.size)} className="rounded-xl border p-3">{[25,50,100].map(x=><option key={x} value={x}>{x} rows</option>)}</select><button className="rounded-xl bg-stone-950 p-3 font-black text-amber-300">Apply</button><Link href={`/admin/goodreturns-cities?tab=${result.tab}`} className="rounded-xl border p-3 text-center font-bold">Clear</Link><a href={`/admin/goodreturns-cities/export?${query(filters,{tab:result.tab,page:"1"})}`} className="rounded-xl bg-amber-400 p-3 text-center font-black">Export {result.tab[0].toUpperCase()+result.tab.slice(1)} CSV</a></form>
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-stone-950 text-white"><tr>{(result.tab==="supported"?["State","RateStack City","GoodReturns City","Provider Slug","Mapping Type","Status"]:result.tab==="unsupported"?["State","City","Status","Reason"]:["State","City","Provider Slug","Failure Reason"]).map(x=><th key={x} className={cell}>{x}</th>)}</tr></thead><tbody className="divide-y">{result.tab==="supported"&&supported.map(row=><tr key={`${row.state}:${row.rateStackCity}`}><td className={cell}>{row.state}</td><td className={cell}>{row.rateStackCity}</td><td className={cell}>{row.providerCity}</td><td className={cell}>{row.providerSlug}</td><td className={cell}>{row.mappingType}</td><td className={cell}><span className="rounded-full bg-emerald-100 px-3 py-1 font-bold text-emerald-800">{row.status}</span></td></tr>)}{result.tab==="unsupported"&&unsupported.map(row=><tr key={`${row.state}:${row.city}`}><td className={cell}>{row.state||"—"}</td><td className={cell}>{row.city}</td><td className={cell}><span className="rounded-full bg-stone-100 px-3 py-1 font-bold">Unsupported</span></td><td className={cell}>{row.reason}</td></tr>)}{result.tab==="failed"&&failed.map(row=><tr key={`${row.state}:${row.city}`}><td className={cell}>{row.state||"—"}</td><td className={cell}>{row.city}</td><td className={cell}>{row.providerSlug||"—"}</td><td className={cell}>{row.reason}</td></tr>)}</tbody></table>{result.total===0&&<p className="p-10 text-center text-stone-500">{result.tab==="failed"?"No failed cities in the latest catalogue synchronization.":"No cities match the selected filters."}</p>}</div>
    <div className="flex justify-between text-sm"><p>{result.total.toLocaleString("en-IN")} rows</p><div className="flex gap-2">{result.page>1&&<Link className="rounded-lg border px-4 py-2" href={`?${query(filters,{tab:result.tab,page:String(result.page-1),size:String(result.size)})}`}>Previous</Link>}<span className="px-3 py-2">Page {result.page} of {pages}</span>{result.page<pages&&<Link className="rounded-lg border px-4 py-2" href={`?${query(filters,{tab:result.tab,page:String(result.page+1),size:String(result.size)})}`}>Next</Link>}</div></div>
  </div>;
}
