"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { requireOrderAdmin } from "@/lib/admin-orders";
import { shiprocketRequest } from "@/lib/shiprocket/client";
import { getShiprocketConfig, publicShiprocketHealth } from "@/lib/shiprocket/config";
const redirectError=(error:unknown)=>error instanceof Error&&"digest" in error&&typeof error.digest==="string"&&error.digest.startsWith("NEXT_REDIRECT");
const done=(message:string,error=false)=>{revalidatePath("/admin/settings/shiprocket");redirect(`/admin/settings/shiprocket?${error?"error":"notice"}=${encodeURIComponent(message)}`)};
export async function testShiprocketAction(){try{await requireOrderAdmin("shiprocket");const config=await getShiprocketConfig();if(!config.enabled)throw new Error("Shiprocket integration disabled.");await shiprocketRequest("/settings/company/pickup",{safeRetry:true});await prisma.systemSetting.upsert({where:{key:"SHIPROCKET_LAST_SUCCESS"},create:{key:"SHIPROCKET_LAST_SUCCESS",value:new Date().toISOString()},update:{value:new Date().toISOString()}});done("Authentication and pickup-location API succeeded.")}catch(error){if(redirectError(error))throw error;await prisma.systemSetting.upsert({where:{key:"SHIPROCKET_LAST_ERROR"},create:{key:"SHIPROCKET_LAST_ERROR",value:error instanceof Error?error.message.slice(0,500):"Test failed"},update:{value:error instanceof Error?error.message.slice(0,500):"Test failed"}});done(error instanceof Error?error.message:"Test failed.",true)}}
export async function fetchPickupLocationsAction(){try{await requireOrderAdmin("shiprocket");const response=await shiprocketRequest("/settings/company/pickup",{safeRetry:true}),data=Array.isArray(response.data)?response.data:[];await prisma.systemSetting.upsert({where:{key:"SHIPROCKET_PICKUP_LOCATIONS"},create:{key:"SHIPROCKET_PICKUP_LOCATIONS",value:JSON.stringify(data)},update:{value:JSON.stringify(data)}});done(`Fetched ${data.length} pickup locations.`)}catch(error){if(redirectError(error))throw error;done(error instanceof Error?error.message:"Pickup fetch failed.",true)}}
export async function savePickupLocationAction(data:FormData){try{const admin=await requireOrderAdmin("shiprocket"),location=String(data.get("pickupLocation")||"").trim();if(!/^[A-Za-z0-9 _.-]{1,100}$/.test(location))throw new Error("Select a valid pickup-location identifier.");await prisma.$transaction([prisma.systemSetting.upsert({where:{key:"SHIPROCKET_PICKUP_LOCATION"},create:{key:"SHIPROCKET_PICKUP_LOCATION",value:location},update:{value:location}}),prisma.adminAuditLog.create({data:{adminUserId:admin.id,action:"SHIPROCKET_PICKUP_LOCATION_CHANGED",targetEntity:"SystemSetting",targetId:"SHIPROCKET_PICKUP_LOCATION",detailsJson:{configured:true},ipAddress:admin.ipAddress}})]);done("Pickup location saved.")}catch(error){if(redirectError(error))throw error;done(error instanceof Error?error.message:"Save failed.",true)}}
export async function getShiprocketHealth(){return publicShiprocketHealth(await getShiprocketConfig())}
