import { NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import { requireOrderAdmin } from "@/lib/admin-orders";

const safe=(value:unknown)=>String(value??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
const money=(value:bigint)=>`₹${(Number(value)/100).toLocaleString("en-IN",{minimumFractionDigits:2})}`;
export async function GET(request:Request,{params}:{params:Promise<{orderId:string}>}){
  try{
    await requireOrderAdmin("view");const {orderId}=await params;const url=new URL(request.url);const type=url.searchParams.get("type")==="packing-slip"?"packing-slip":"invoice";const download=url.searchParams.get("download")==="1";
    const order=await prisma.shopOrder.findUnique({where:{id:orderId},include:{user:true}});
    if(!order)return NextResponse.json({success:false,error:{message:"Order not found."}},{status:404});
    const prices=type==="invoice"?`<h2>Price breakup</h2><div class="r"><span>Metal Value</span><b>${money(order.metalValuePaise)}</b></div><div class="r"><span>Service Charge</span><b>${money(order.serviceChargePaise)}</b></div><div class="r"><span>GST (${order.gstBasisPoints/100}%)</span><b>${money(order.gstPaise)}</b></div><div class="r"><span>Shipping</span><b>${order.shippingAmountPaise===0n?"FREE":money(order.shippingAmountPaise)}</b></div><div class="r total"><span>Total Payable</span><b>${money(order.totalAmountPaise)}</b></div>`:"";
    const html=`<!doctype html><html><head><meta charset="utf-8"><title>${safe(order.orderNumber)}</title><style>body{font:14px Arial;color:#292524;max-width:850px;margin:auto;padding:38px}.brand{background:#1c1917;color:#f5c96a;padding:24px;border-radius:14px}h1{margin:0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:24px}.card{border:1px solid #ddd;border-radius:12px;padding:16px;margin-top:20px}.r{display:flex;justify-content:space-between;border-bottom:1px solid #eee;padding:9px 0}.total{font-size:18px;color:#92400e}@media print{button{display:none}}</style></head><body><div class="brand"><h1>RateStack</h1><p>${type==="invoice"?"Tax Invoice":"Packing Slip"} · ${safe(order.orderNumber)}</p></div><div class="grid"><div class="card"><h2>Customer</h2><p>${safe(order.customerName||order.user.fullName)}<br>${safe(order.customerEmail||order.user.email)}<br>${safe(order.customerPhone||order.user.phone)}</p></div><div class="card"><h2>Delivery</h2><p>${safe(order.addressLine1)} ${safe(order.addressLine2)}<br>${safe(order.deliveryCity)}, ${safe(order.deliveryDistrict)}<br>${safe(order.deliveryState)} ${safe(order.deliveryPincode)}</p></div></div><div class="card"><h2>Product</h2><p><b>${safe(order.productName)}</b><br>${safe(order.metalType)} · ${safe(order.purity)} · ${safe(order.weightGrams)}g × ${order.quantity}</p></div><div class="card">${prices}<h2>Payment & shipment</h2><p>${safe(order.gateway)} · ${safe(order.paymentStatus)} · Payment ID: ${safe(order.gatewayPaymentId||"Pending")}</p><p>Courier: ${safe(order.courierPartner||"Pending")} · AWB: ${safe(order.trackingNumber||"Pending")}</p><p>GST details: GST charged at ${order.gstBasisPoints/100}% on applicable value.</p></div><button onclick="print()">Print document</button></body></html>`;
    return new NextResponse(html,{headers:{"Content-Type":"text/html; charset=utf-8","Content-Disposition":`${download?"attachment":"inline"}; filename="${type}-${order.orderNumber}.html"`,"Cache-Control":"private, no-store"}});
  }catch{return NextResponse.json({success:false,error:{message:"Admin authorization required."}},{status:403});}
}
