import { NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { authenticateSchemeUserFromRequest } from "@/lib/schemes/user-auth";
const schema=z.object({token:z.string().min(20).max(4096),platform:z.enum(["ANDROID","IOS","WEB"]).default("ANDROID"),deviceName:z.string().max(100).optional(),appVersion:z.string().max(30).optional()});
const authError=()=>NextResponse.json({success:false,error:{message:"Authentication required."}},{status:401});
export async function GET(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return authError();const devices=await prisma.pushDeviceToken.findMany({where:{customerId:auth.userId,isActive:true},select:{id:true,platform:true,deviceName:true,appVersion:true,lastSeenAt:true,createdAt:true},orderBy:{lastSeenAt:"desc"}});return NextResponse.json({success:true,data:devices})}
export async function POST(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return authError();const parsed=schema.safeParse(await request.json().catch(()=>null));if(!parsed.success)return NextResponse.json({success:false,error:{code:"INVALID_DEVICE_TOKEN",message:"Invalid device registration."}},{status:400});const device=await prisma.pushDeviceToken.upsert({where:{token:parsed.data.token},update:{customerId:auth.userId,platform:parsed.data.platform,deviceName:parsed.data.deviceName,appVersion:parsed.data.appVersion,isActive:true,revokedAt:null,lastSeenAt:new Date()},create:{customerId:auth.userId,...parsed.data}});return NextResponse.json({success:true,data:{id:device.id,platform:device.platform,lastSeenAt:device.lastSeenAt}})}
export async function DELETE(request:Request){const auth=await authenticateSchemeUserFromRequest(request);if(!auth)return authError();const body=await request.json().catch(()=>null),token=typeof body?.token==="string"?body.token:"";if(!token)return NextResponse.json({success:false,error:{message:"Token is required."}},{status:400});await prisma.pushDeviceToken.updateMany({where:{customerId:auth.userId,token},data:{isActive:false,revokedAt:new Date()}});return NextResponse.json({success:true,data:{revoked:true}})}
