"use server";
import { revalidatePath } from "next/cache";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requireOrderAdmin, recordAdminAudit } from "@/lib/admin-orders";
import { enqueueNotification, safeDeepLink } from "@/lib/notifications/outbox";
import { processNotificationBatch } from "@/lib/notifications/worker";
import { sendPush } from "@/lib/notifications/providers";
import { hasAdminPermission } from "@/lib/admin-permissions";
const broadcastSchema=z.object({title:z.string().min(2).max(100),message:z.string().min(2).max(500),deepLink:z.string().max(200),audience:z.enum(["ALL","GOLD","SILVER"]),confirm:z.literal("CONFIRM")});
const manualRuns=new Map<string,number>();
const notificationAdmin=async()=>{const admin=await requireOrderAdmin("status");if(!hasAdminPermission(admin.role,"NOTIFICATION_SEND"))throw new Error("ADMIN_FORBIDDEN");return admin};
export type NotificationActionState={message:string;processed?:number;sent?:number;failed?:number;skipped?:number};
export async function processPendingNotificationsAction(_state:NotificationActionState,_data:FormData):Promise<NotificationActionState>{void _state;void _data;const admin=await notificationAdmin(),now=Date.now(),last=manualRuns.get(admin.id)||0;if(now-last<10_000)return {message:"Please wait before processing notifications again."};manualRuns.set(admin.id,now);const result=await processNotificationBatch(25);await recordAdminAudit(admin,"NOTIFICATION_WORKER_RUN","notification-worker",result);revalidatePath("/admin/notifications");return {message:"Manual worker run completed.",processed:result.processed,sent:result.sent,failed:result.failed,skipped:result.skipped}}
export async function retryFailedNotificationsAction(_state:NotificationActionState,_data:FormData):Promise<NotificationActionState>{void _state;void _data;const admin=await notificationAdmin();const result=await prisma.notificationOutbox.updateMany({where:{status:"FAILED"},data:{status:"PENDING",attemptCount:0,scheduledAt:new Date(),failedAt:null,failureReason:null}});await recordAdminAudit(admin,"FAILED_NOTIFICATIONS_REQUEUED","notification-worker",{count:result.count});revalidatePath("/admin/notifications");return {message:`${result.count} failed notifications queued for retry.`}}
export async function sendTestPushAction(_state:NotificationActionState,data:FormData):Promise<NotificationActionState>{const admin=await notificationAdmin(),deviceId=String(data.get("deviceId")||"");const device=await prisma.pushDeviceToken.findFirst({where:{id:deviceId,isActive:true},select:{id:true,token:true,customerId:true}});if(!device)return {message:"Select an active Android device."};const result=await sendPush(device.token,"RateStack Test Notification","Firebase push delivery is configured correctly.",{destination:"DASHBOARD",orderId:"",tracking:"false",metal:"",deepLink:"/shop/orders",channel:"orders"});await recordAdminAudit(admin,"TEST_PUSH_SENT",device.customerId,{deviceId:device.id,providerAccepted:!result.disabled,messageIdPresent:Boolean(result.messageId)});revalidatePath("/admin/notifications");return {message:result.disabled?"Firebase is disabled; no push was sent.":"Firebase accepted the test push."}}
export async function retryNotificationAction(data:FormData){const admin=await notificationAdmin(),id=String(data.get("id")||"");await prisma.notificationOutbox.update({where:{id},data:{status:"PENDING",attemptCount:0,scheduledAt:new Date(),failedAt:null,failureReason:null}});await recordAdminAudit(admin,"NOTIFICATION_RETRIED",id);revalidatePath("/admin/notifications")}
export async function broadcastNotificationAction(data:FormData){const admin=await notificationAdmin(),parsed=broadcastSchema.safeParse(Object.fromEntries(data));if(!parsed.success)throw new Error("INVALID_BROADCAST");const deepLink=safeDeepLink(parsed.data.deepLink),users=await prisma.schemeUser.findMany({where:{isActive:true,...(parsed.data.audience==="ALL"?{}:{rateAlertPreferences:{some:{metal:parsed.data.audience,enabled:true}}})},select:{id:true},take:1000});const batch=`broadcast:${Date.now()}:${admin.id}`;await Promise.all(users.map(user=>enqueueNotification({customerId:user.id,eventType:"ADMIN_BROADCAST",title:parsed.data.title,body:parsed.data.message,channels:["PUSH"],payload:{deepLink,destination:"DASHBOARD",channel:"promotions"},deduplicationKey:`${batch}:${user.id}`})));await recordAdminAudit(admin,"NOTIFICATION_BROADCAST",batch,{audience:parsed.data.audience,recipientCount:users.length,deepLink});revalidatePath("/admin/notifications")}
