CREATE TYPE "AdminRole" AS ENUM ('SUPER_ADMIN','ORDER_MANAGER','FINANCE','FULFILLMENT','SUPPORT','VIEWER');
CREATE TYPE "ShopOrderStatus" AS ENUM ('PAYMENT_PENDING','PAYMENT_FAILED','PAYMENT_VERIFIED','ORDER_CONFIRMED','PROCESSING','PACKED','READY_TO_SHIP','SHIPPED','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','CANCEL_REQUESTED','CANCELLED','RETURN_REQUESTED','RETURNED','REFUND_PENDING','REFUNDED');
CREATE TYPE "ShopShipmentStatus" AS ENUM ('NOT_CREATED','READY_TO_SHIP','PICKUP_SCHEDULED','SHIPPED','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','RETURNED');
CREATE TYPE "TrackingEventSource" AS ENUM ('ADMIN','PAYMENT_GATEWAY','SHIPROCKET','SYSTEM');
CREATE TYPE "PaymentVerificationResult" AS ENUM ('VERIFIED','FAILED','MANUAL_REVIEW');
CREATE TYPE "ShopRefundStatus" AS ENUM ('NOT_REQUIRED','PENDING','PARTIALLY_REFUNDED','FULLY_REFUNDED','FAILED');
ALTER TABLE "AdminUser" ADD COLUMN "role" "AdminRole" NOT NULL DEFAULT 'ORDER_MANAGER';
UPDATE "ShopOrder" SET "orderStatus"=CASE WHEN "orderStatus" IN ('CONFIRMED','PAID') THEN 'ORDER_CONFIRMED' WHEN "orderStatus"='FAILED' THEN 'PAYMENT_FAILED' WHEN "orderStatus" IN ('CREATED','PENDING') THEN 'PAYMENT_PENDING' ELSE "orderStatus" END;
ALTER TABLE "ShopOrder" ALTER COLUMN "orderStatus" DROP DEFAULT;
ALTER TABLE "ShopOrder" ALTER COLUMN "orderStatus" TYPE "ShopOrderStatus" USING "orderStatus"::"ShopOrderStatus";
ALTER TABLE "ShopOrder" ALTER COLUMN "orderStatus" SET DEFAULT 'PAYMENT_PENDING';
UPDATE "ShopOrder" SET "shipmentStatus"=CASE WHEN "shipmentStatus" IS NULL OR "shipmentStatus" IN ('Awaiting payment','Processing','No shipment') THEN 'NOT_CREATED' WHEN UPPER(REPLACE("shipmentStatus",' ','_')) IN ('READY_TO_SHIP','PICKUP_SCHEDULED','SHIPPED','IN_TRANSIT','OUT_FOR_DELIVERY','DELIVERED','CANCELLED','RETURNED') THEN UPPER(REPLACE("shipmentStatus",' ','_')) ELSE 'NOT_CREATED' END;
ALTER TABLE "ShopOrder" ALTER COLUMN "shipmentStatus" TYPE "ShopShipmentStatus" USING "shipmentStatus"::"ShopShipmentStatus";
ALTER TABLE "ShopOrder" ALTER COLUMN "shipmentStatus" SET NOT NULL;
ALTER TABLE "ShopOrder" ALTER COLUMN "shipmentStatus" SET DEFAULT 'NOT_CREATED';
ALTER TABLE "ShopOrder" ADD COLUMN "pickupAt" TIMESTAMP(3), ADD COLUMN "deliveredAt" TIMESTAMP(3), ADD COLUMN "publicTrackingUrl" TEXT, ADD COLUMN "shipmentId" TEXT, ADD COLUMN "discountAmountPaise" BIGINT NOT NULL DEFAULT 0, ADD COLUMN "cancellationReason" TEXT, ADD COLUMN "cancellationPaymentCaptured" BOOLEAN, ADD COLUMN "cancellationRefundRequired" BOOLEAN, ADD COLUMN "cancellationShipmentCreated" BOOLEAN;
CREATE TABLE "OrderStatusHistory" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"status" "ShopOrderStatus" NOT NULL,"publicMessage" TEXT NOT NULL,"internalNote" TEXT,"source" "TrackingEventSource" NOT NULL,"adminUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "OrderStatusHistory_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShipmentTrackingEvent" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"status" TEXT NOT NULL,"publicMessage" TEXT NOT NULL,"internalNote" TEXT,"source" "TrackingEventSource" NOT NULL,"adminUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "ShipmentTrackingEvent_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminOrderNote" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"body" TEXT NOT NULL,"adminUserId" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdminOrderNote_pkey" PRIMARY KEY ("id"));
CREATE TABLE "PaymentVerification" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"gateway" TEXT NOT NULL,"gatewayOrderId" TEXT,"gatewayPaymentId" TEXT,"verifiedAmountPaise" BIGINT,"signatureValid" BOOLEAN,"result" "PaymentVerificationResult" NOT NULL,"resultMessage" TEXT NOT NULL,"responseJson" JSONB,"adminUserId" TEXT,"verifiedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "PaymentVerification_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ShopRefund" ("id" TEXT NOT NULL,"orderId" TEXT NOT NULL,"amountPaise" BIGINT NOT NULL,"gatewayRefundId" TEXT,"status" "ShopRefundStatus" NOT NULL DEFAULT 'PENDING',"reason" TEXT NOT NULL,"initiatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"completedAt" TIMESTAMP(3),"failureReason" TEXT,"adminUserId" TEXT NOT NULL,CONSTRAINT "ShopRefund_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AdminAuditLog" ("id" TEXT NOT NULL,"adminUserId" TEXT NOT NULL,"action" TEXT NOT NULL,"targetEntity" TEXT NOT NULL,"targetId" TEXT NOT NULL,"detailsJson" JSONB,"ipAddress" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AdminAuditLog_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "PaymentVerification_orderId_key" ON "PaymentVerification"("orderId");
CREATE INDEX "OrderStatusHistory_orderId_createdAt_idx" ON "OrderStatusHistory"("orderId","createdAt");
CREATE INDEX "ShipmentTrackingEvent_orderId_createdAt_idx" ON "ShipmentTrackingEvent"("orderId","createdAt");
CREATE INDEX "AdminOrderNote_orderId_createdAt_idx" ON "AdminOrderNote"("orderId","createdAt");
CREATE INDEX "ShopRefund_orderId_initiatedAt_idx" ON "ShopRefund"("orderId","initiatedAt");
CREATE INDEX "AdminAuditLog_targetEntity_targetId_createdAt_idx" ON "AdminAuditLog"("targetEntity","targetId","createdAt");
CREATE INDEX "AdminAuditLog_adminUserId_createdAt_idx" ON "AdminAuditLog"("adminUserId","createdAt");
ALTER TABLE "OrderStatusHistory" ADD CONSTRAINT "OrderStatusHistory_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "OrderStatusHistory" ADD CONSTRAINT "OrderStatusHistory_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShipmentTrackingEvent" ADD CONSTRAINT "ShipmentTrackingEvent_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShipmentTrackingEvent" ADD CONSTRAINT "ShipmentTrackingEvent_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "AdminOrderNote" ADD CONSTRAINT "AdminOrderNote_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AdminOrderNote" ADD CONSTRAINT "AdminOrderNote_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PaymentVerification" ADD CONSTRAINT "PaymentVerification_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "PaymentVerification" ADD CONSTRAINT "PaymentVerification_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "ShopRefund" ADD CONSTRAINT "ShopRefund_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "ShopOrder"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ShopRefund" ADD CONSTRAINT "ShopRefund_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "AdminAuditLog" ADD CONSTRAINT "AdminAuditLog_adminUserId_fkey" FOREIGN KEY ("adminUserId") REFERENCES "AdminUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
