import Link from "next/link";
import { requireCustomerAdmin } from "@/lib/customer-admin";
import { customerUsageCount, customerUsageMetrics, customerUsageRows, usageRow, type UsageFilters } from "@/lib/customer-usage-report";

export const dynamic = "force-dynamic";
const dt = (value: Date | null) => value ? value.toLocaleString("en-IN", { timeZone: "Asia/Kolkata" }) : "—";

export default async function CustomerUsagePage({ searchParams }: { searchParams: Promise<UsageFilters> }) {
  await requireCustomerAdmin();
  const filters = await searchParams, page = Math.max(1, Number(filters.page) || 1), take = 25;
  const [metrics, users, total] = await Promise.all([customerUsageMetrics(), customerUsageRows(filters, take, (page - 1) * take), customerUsageCount(filters)]);
  const rows = users.map(usageRow), query = new URLSearchParams(Object.entries(filters).filter(([, v]) => v) as [string, string][]);
  return <div className="space-y-6"><div><p className="text-xs font-black uppercase tracking-[.2em] text-amber-700">Customers</p><h1 className="font-display text-4xl font-bold">Customer Usage &amp; Login Overview</h1><p className="mt-2 text-stone-600">Distinct customer accounts across the RateStack website and Android app.</p></div>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Object.entries({"Total Registered Customers":metrics.registered,"Total Unique Customers Who Have Logged In":metrics.unique,"Android App Users":metrics.android,"Website Users":metrics.web,"Users on Both Platforms":metrics.both,"Active Today":metrics.activeToday,"Active in Last 7 Days":metrics.active7,"Active in Last 30 Days":metrics.active30,"Never Logged In":metrics.never}).map(([label,value])=><article key={label} className="rounded-2xl border bg-white p-5"><p className="text-xs font-black uppercase text-stone-500">{label}</p><p className="mt-2 text-3xl font-black">{value.toLocaleString("en-IN")}</p></article>)}</section>
    <form className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-3 xl:grid-cols-6"><input name="q" defaultValue={filters.q} placeholder="Name, mobile or email" className="rounded-xl border p-3 xl:col-span-2"/><select name="platform" defaultValue={filters.platform||"all"} className="rounded-xl border p-3"><option value="all">All platforms</option><option value="web">Website</option><option value="android">Android</option><option value="both">Both</option></select><select name="status" defaultValue={filters.status||"all"} className="rounded-xl border p-3"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option></select><select name="active" defaultValue={filters.active||"all"} className="rounded-xl border p-3"><option value="all">Any activity</option><option value="today">Today</option><option value="7">Last 7 days</option><option value="30">Last 30 days</option><option value="custom">Custom</option></select><select name="method" defaultValue={filters.method||""} className="rounded-xl border p-3"><option value="">All login methods</option>{["MOBILE_PASSWORD","EMAIL_PASSWORD","GOOGLE","OTP","SESSION_RESTORE"].map(x=><option key={x}>{x}</option>)}</select><input type="date" name="from" defaultValue={filters.from} className="rounded-xl border p-3"/><input type="date" name="to" defaultValue={filters.to} className="rounded-xl border p-3"/><button className="rounded-xl bg-stone-950 p-3 font-black text-amber-300">Apply filters</button><Link href="/admin/customers/usage" className="rounded-xl border p-3 text-center font-bold">Clear</Link><a href={`/admin/customers/usage/export?${query}`} className="rounded-xl bg-amber-400 p-3 text-center font-black">Export filtered CSV</a></form>
    <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[1500px] w-full text-left text-sm"><thead className="bg-stone-950 text-white"><tr>{["Customer","Mobile","Email","Platform","Login methods","First login","Last login","Last active","Successful logins","Android version","Status"].map(x=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody className="divide-y">{rows.map(row=><tr key={row.id}><td className="p-3 font-bold">{row.fullName}</td><td>{row.phone||"—"}</td><td>{row.email||"—"}</td><td>{row.platform}</td><td>{row.methods}</td><td>{dt(row.firstLogin)}</td><td>{dt(row.lastLogin)}</td><td>{dt(row.lastActive)}</td><td>{row.loginCount}</td><td>{row.appVersion||"—"}</td><td>{row.isActive&&row.accountStatus==="ACTIVE"?"Active":"Inactive"}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-10 text-center text-stone-500">No customers match these filters.</p>}</div>
    <div className="flex justify-between"><p className="text-sm text-stone-500">{total.toLocaleString("en-IN")} filtered customers</p><div className="flex gap-2">{page>1&&<Link className="rounded-lg border px-4 py-2" href={`?${new URLSearchParams({...Object.fromEntries(query),page:String(page-1)})}`}>Previous</Link>}{page*take<total&&<Link className="rounded-lg border px-4 py-2" href={`?${new URLSearchParams({...Object.fromEntries(query),page:String(page+1)})}`}>Next</Link>}</div></div>
  </div>;
}
